/* GENERATED by scripts/build-family-lps.py from scripts/family_lp_config.py. Edit the Python config, not this file. */
window.SH_FAMILY = {
  "endpoint": "/.netlify/functions/family-inquiry",
  "states": [
    "GA",
    "AL",
    "TN",
    "FL",
    "NC",
    "SC"
  ],
  "noticeVersion": "fo-notice-2026-09-11",
  "phoneE164": "+14709704979",
  "phoneDisplay": "(470) 970-4979",
  "timeoutMs": 15000,
  "tracking": {
    "ga4Id": "",
    "ga4OnSensitivePage": false,
    "metaPixelId": "",
    "capi": false
  }
};
