# -*- coding: utf-8 -*-
"""DSCR persona LP content, part B (LP010-LP017). See dscr_lp_config_a.py."""

PAGES_B = [
dict(id="DSCR-LP010", slug="long-term-rentals", label="Long-term rental owners",
 angles=["DSCR-A022","DSCR-A028"], index=True,
 query="dscr loan long term rental lease requirements",
 title="DSCR for Long-Term Rentals: Lease and Costs | Stonehaven",
 desc="How lease terms, eligible rent and operating costs affect a DSCR review of a long-term rental, with management and maintenance clearly separated from the ratio.",
 h1="Review the lease. Then review the loan",
 sub="For a leased rental, the file starts with the lease: what it says, what it supports, and what the lender's ratio counts against it.",
 answer="For long-term rentals, DSCR programs size eligible rent, typically the lower of the lease or the appraiser's market analysis, against the qualifying payment (PITIA). The relevant limitation, stated where it belongs: management fees, maintenance and vacancy are typically not in the residential qualification ratio, but they are absolutely in your ownership economics. A loan can qualify while the operation underperforms; review both.",
 scen_h="An illustrative leased-rental review",
 scen=["An owner refinances a rental leased at $2,350 where the appraiser's market analysis says $2,150. Under common program treatment the lower figure drives the ratio, which changes leverage and proceeds versus the owner's expectation. Meanwhile professional management takes its percentage of the actual $2,350 every month. Illustrative example, not a customer.",
      "Neither number is wrong. They answer different questions, and the review keeps them straight."],
 fit_h="Where the leased long-term rental sits well",
 fit=["A stabilized lease with market-supported rent is the cleanest DSCR evidence there is, which is why long-term rentals are the product's home ground. Conventional financing also recognizes rental income under its own rules and can price well; the comparison stays worth running.",
      "Where the lease is above market, expect the market figure to govern qualification. Where it is below market, the lease may govern instead. The direction of the gap shapes the whole file."],
 module=dict(type="checklist", h="Lease and expense checklist for the review",
  intro="What a complete long-term rental file looks like before anyone applies:",
  items=[("The lease itself","Term, rent, concessions, deposits and any options. Month-to-month versus term leases can be treated differently by programs."),
         ("Rent support","How the lease rent compares with the appraiser's likely market analysis. A large gap in either direction is a finding, not a footnote."),
         ("Payment reality (PITIA)","Current taxes as they will be assessed, an actual insurance quote, and association dues if any."),
         ("Operating ledger","Management percentage, recent maintenance history, vacancy pattern. Outside the ratio, inside your return."),
         ("Tenancy quality","Payment history and time in place. Underwriting may not price it, but your risk assessment should.")]),
 qual=["Eligible rent treatment: lease versus market analysis per program",
       "Lease form and term rules",
       "Property condition and appraisal results",
       "Credit, leverage and reserves as everywhere",
       "Ownership vesting if held in an entity"],
 obj=[("My lease is above market; will I get credit for it?","Commonly the ratio uses the lower of lease and market analysis, so above-market rent may not fully count for qualification, even though you actually collect it. Plan leverage on the counted number."),
      ("Management eats my margin; does the lender care?","Typically not in the residential ratio, which is exactly why you should: the loan can qualify while your net after management and maintenance disappoints. The review shows the owner column too.")],
 faqs=[("Does a month-to-month tenancy hurt the file?","Programs vary in treating month-to-month versus term leases; some weigh the market analysis more heavily. It is a program fact to check rather than a general rule."),
       ("What if the property is between tenants?","Some programs consider rent-ready vacant properties on the appraiser's market rent; a signed lease is stronger evidence. For 1-4 unit refinances, vacancy rules vary by program and are worth confirming early."),
       ("Do utilities or landlord-paid services change the ratio?","The standard residential ratio centers on rent against PITIA; landlord-paid operating costs sit outside it but squarely inside your cash flow. List them anyway; the review reads both columns."),
       ("Will a rent increase mid-process help?","Underwriting uses the documented evidence at review time under program rules; a new lease can change the file if timing permits. Do not build the plan on rent that is not yet on paper."),
       ("Is my long-term rental better refinanced conventionally?","Sometimes, particularly for strong personal-income files. The comparison is total cost under both paths, and the review should name the winner for your numbers.")],
 related=["experienced-landlords","rate-and-term-refinance","2-4-unit-properties"]),

dict(id="DSCR-LP011", slug="short-term-rentals", label="Short-term rental operators",
 angles=["DSCR-A021"], index=True,
 query="dscr loan for airbnb str income requirements",
 title="DSCR for Short-Term Rentals: The Reality Check | Stonehaven",
 desc="What to verify before considering DSCR for an STR: legal use, documented income, seasonality, property restrictions and program experience rules.",
 h1="An STR forecast needs a financing reality check",
 sub="Short-term rental projections are the most optimistic documents in real estate. The financing review is where the forecast meets what a program will actually count.",
 answer="Some DSCR programs accept short-term rental income under specific rules: documented operating history or defined market-rent treatments, legal-use verification, and in some programs operator-experience requirements. The relevant limitation: STR eligibility is select-program, not universal, and the revenue a program counts is usually well below a listing-site screenshot. Legal use is checked, seasonality is real, and no page can promise a specific STR outcome.",
 scen_h="An illustrative STR financing question",
 scen=["An operator with a cabin grossing $68,000 in bookings last year wants to refinance. The program review will not start from $68,000: it will ask what documentation supports the figure, what the property's legal STR status is, what the market rent would be as a long-term rental, and which of those numbers the program's rules count. Illustrative example, not a customer.",
      "The forecast that survives that review is the one worth financing against."],
 fit_h="STR income against long-term treatment",
 fit=["Where a program counts documented STR revenue, strong operating history can support the file. Where it does not, the property may still finance on its long-term market rent, a lower but sturdier number. Both paths are legitimate; they produce different leverage.",
      "If the deal only works when peak-season revenue is annualized, it does not work. Seasonality belongs in the plan, not just the disclosure."],
 module=dict(type="checklist", h="The STR verification list, in order",
  intro="Five gates, each checked before the next matters:",
  items=[("Legal use, in writing","Zoning, local ordinance, permits or licenses, and any HOA or condo restrictions. An STR ban discovered in underwriting ends the file late; check first."),
         ("Documented income","A managed operating statement or booking-platform history over a defined period, not screenshots of good months. Programs specify what counts."),
         ("Seasonality mapped","Twelve months tell the truth that July does not. Review the trough months against the payment, not the average against it."),
         ("Property and market restrictions","Property types and locations carry program-specific STR rules; resort and condotel classifications route differently."),
         ("Operator experience","Some programs restrict newer STR operators or apply overlays. Your history is part of the file.")]),
 qual=["Program-specific STR income acceptance and documentation rules",
       "Legal-use verification for the specific address",
       "Property type and location eligibility",
       "Operator experience under some programs",
       "Credit, leverage and reserves as everywhere"],
 obj=[("My gross bookings are strong; is that enough?","Gross bookings are the top of the funnel. Programs count defined, documented figures, and platform fees, cleaning and management are between your gross and your net. The counted number is what finances."),
      ("What if my city changes the rules?","Regulatory risk is real and belongs in your hold plan. A financing review verifies today's legal status; it cannot insure tomorrow's ordinance.")],
 faqs=[("Can Airbnb income qualify for a DSCR loan?","Under select programs, documented short-term rental income can be considered per their rules. Eligibility is program-specific: history requirements, treatments and restrictions vary, which is why the review confirms the actual program fit."),
       ("How much history do I need?","Programs define their own documentation periods and sources. Newer operations may finance on long-term market rent instead, at that number's leverage."),
       ("Does a condotel count as an STR for financing?","Condotels are a distinct property classification with their own program treatment, separate from an STR house or cabin. The classification changes the program set before the income question arrives."),
       ("Will seasonality lower what I qualify for?","The counted income figure reflects the program's documentation rules over a defined period, which inherently absorbs seasonality. Your operating plan should absorb it too."),
       ("Is a vacation home I sometimes use eligible?","Personal-use patterns can change classification and program fit. Be precise about actual use in the review; the wrong classification found late costs the most.")],
 related=["out-of-state-investors","long-term-rentals","llc-investors"]),

dict(id="DSCR-LP012", slug="rate-and-term-refinance", label="Rate-and-term refinance",
 angles=["DSCR-A015","DSCR-A025"], index=True,
 query="refinance rental property loan break even dscr",
 title="Rental Rate-and-Term Refinance, Earned | Stonehaven",
 desc="Would replacing the current rental loan improve the structure? Cost, payment, term and break-even comparison against keeping the loan you have.",
 h1="A new rental loan should earn its place",
 sub="Restructuring debt is a decision with a price. This page is the math that says whether the replacement deserves the fee.",
 answer="A rate-and-term refinance replaces the current rental loan with a new one without meaningful cash out: the point is structure, payment, term or product change rather than proceeds. Qualification runs on eligible rent against the new qualifying payment (PITIA). The relevant limitation: closing costs are certain and savings are conditional, so the decision lives in the break-even math and the remaining hold period, not in the monthly payment alone.",
 scen_h="An illustrative restructure decision",
 scen=["An owner carries a rental loan with a payment structure that no longer fits the hold plan. The proposed refinance changes the payment and the term; it also costs real fees and may carry new prepayment terms. Whether it earns its place depends on the break-even month against how long the owner will actually keep the property and loan. Illustrative example, not a customer.",
      "A refinance that breaks even in year four is a poor purchase for an owner planning to sell in year two."],
 fit_h="Replace, keep, or wait",
 fit=["Keeping the current loan costs nothing today and preserves known terms. Replacing it can fix a structural problem: a payment that will change, a maturity approaching, a product mismatch with the hold plan. Waiting is legitimate when neither pressure exists.",
      "This page is deliberately not about accessing equity; that comparison, with its different rules and economics, lives on the cash-out page. Keeping the two decisions separate keeps both honest."],
 module=dict(type="table", h="The break-even worksheet",
  intro="Six lines decide a rate-and-term refinance. Illustrative structure; the review fills real numbers:",
  cols=("Line","Keep the current loan","Refinance"),
  items=[("Monthly payment (PITIA)","Known","Proposed"),
         ("All-in closing costs","None","Itemized, certain"),
         ("Monthly difference","Baseline","Payment change, if any"),
         ("Break-even month","Not applicable","Costs divided by monthly difference"),
         ("Expected remaining hold","Your plan","Same plan, tested against break-even"),
         ("Prepayment terms","Existing note's","New note's, including any new exposure")]),
 qual=["Eligible rent at today's evidence against the new payment",
       "Seasoning and refinance-classification rules",
       "Credit, leverage and reserves",
       "Prepayment terms on both notes",
       "Appraisal at current value"],
 obj=[("Rates and payments are not published here; how do I compare?","Deliberately so: volatile numbers do not belong on a static page. The comparison uses your actual quotes at review time, itemized, against your actual current note. The worksheet's structure is the constant."),
      ("The new payment is lower; is that not the answer?","Only with the costs and the calendar attached. Lower payment, real fees and a longer effective horizon can still lose to keeping the loan. Break-even against the hold answers it.")],
 faqs=[("What counts as rate-and-term versus cash-out?","Classifications turn on proceeds and payoff structure, and each carries different rules on leverage and seasoning. The review classifies the scenario before comparing, because the classification changes the rules being compared."),
       ("Do prepayment terms on my current loan matter?","Yes, twice: any exit cost on the current note belongs in the refinance cost total, and the new note's prepayment terms belong in your future flexibility. Both are itemized in the review."),
       ("Does the property need to re-qualify?","Yes: the refinance is a new loan, sized on today's eligible rent, today's appraisal and current program rules. A property that qualified years ago is not automatically the same file today."),
       ("When is waiting the right call?","When no structural pressure exists (no payment change coming, no maturity, no product mismatch) and break-even math is marginal. A review that says wait is doing its job."),
       ("Can I fold a small amount of cash into a rate-and-term?","Classification rules define how much incidental cash keeps rate-and-term treatment; beyond it, cash-out rules apply. Where your scenario lands is a rules question the review settles.")],
 related=["cash-out-refinance","hold-or-sell","bridge-loan-refinance"]),

dict(id="DSCR-LP013", slug="llc-investors", label="LLC and partnership owners",
 angles=["DSCR-A024"], index=True,
 query="dscr loan llc entity requirements personal guarantee",
 title="DSCR Loans and LLC Ownership | Stonehaven",
 desc="How entity ownership and borrower obligations interact on a DSCR loan: vesting, entity documents and guarantor questions, stated without nonrecourse promises.",
 h1="Review the property and the ownership structure",
 sub="The deal has two architectures: the property's numbers and the entity that holds them. Underwriting reads both.",
 answer="Some DSCR programs permit vesting in an LLC or partnership, subject to entity documentation and, commonly, personal guaranties from the individuals behind the entity. The relevant limitation, plainly: entity vesting does not make a loan nonrecourse, and nothing here is tax advice. The entity changes how title is held and what papers the file needs; it does not remove the humans from the obligation.",
 scen_h="An illustrative entity file",
 scen=["Two partners hold a rental in a two-member LLC and want to refinance. The file needs the entity's formation documents, standing, and authority to borrow; the program's rules decide who signs and who guarantees. A missing operating agreement or a lapsed registration stalls the closing more often than the property does. Illustrative example, not a customer.",
      "The entity questions are all answerable in advance; the only expensive version is answering them during underwriting."],
 fit_h="Entity vesting against personal title",
 fit=["Investors choose entities for liability separation, partnership structure and administration; those are legal and business decisions to make with your own advisers. On the financing side, entity vesting is commonly available under DSCR programs and less flexible conventionally, which is one practical reason the structures pair often.",
      "If the entity exists only to hold this loan, weigh the administrative cost honestly. If it exists for real structural reasons, prepare its papers like part of the loan file, because they are."],
 module=dict(type="checklist", h="Entity-document readiness list",
  intro="What underwriting typically wants from the entity, ready before it asks:",
  items=[("Formation documents","Articles or certificate of formation for the LLC or partnership agreement equivalents, as filed."),
         ("Operating agreement","Current, signed, and consistent with who claims authority to borrow. Amendments included."),
         ("Good standing","Active status in the formation state and, where required, registration where the property sits."),
         ("EIN and ownership map","The entity's tax ID and a clear picture of members or partners and percentages, matching the agreement."),
         ("Authority and signers","Who resolves to borrow, who signs, and which individuals the program requires as guarantors.")]),
 qual=["Entity type and program vesting rules",
       "Guarantor requirements for the individuals behind the entity",
       "Entity standing and registration in the relevant states",
       "Credit of the guaranteeing individuals",
       "The property's own numbers, as everywhere"],
 obj=[("I wanted the LLC so the loan would not touch me personally.","Expect personal guaranties under common program rules; entity vesting is about title and structure, not escape from the obligation. Nothing on this page is represented as nonrecourse."),
      ("Is the LLC worth it for taxes?","That is a question for your tax adviser, deliberately unanswered here. The financing review covers what the entity does to the file, not what it does to your return.")],
 faqs=[("Can my LLC be on title for a DSCR loan?","Entity vesting is permitted under some programs, with entity documentation and guarantor requirements. Whether your entity and program line up is a review question."),
       ("Who has to guarantee the loan?","Program rules define which members or partners guarantee, commonly tied to ownership percentage or control. The individuals' credit then becomes part of the file."),
       ("Does a multi-member LLC complicate the file?","It adds signers, potentially guarantors, and consistency checks across the agreement. Complication is manageable when the papers agree with each other; painful when they do not."),
       ("Can I transfer a personally held property into my LLC at refinance?","Title changes interact with seasoning and program rules and deserve deliberate sequencing. Raise the intended transfer at review, not at closing."),
       ("Does the entity's home state matter if the property is elsewhere?","Formation state, property state and registration requirements can all apply. The standing checklist above covers what underwriting typically checks; your attorney covers the rest.")],
 related=["self-employed-investors","portfolio-growth","cash-out-refinance"]),

dict(id="DSCR-LP014", slug="2-4-unit-properties", label="2-4 unit investors",
 angles=["DSCR-A023"], index=True,
 query="dscr loan 2-4 unit multifamily rent roll",
 title="DSCR for 2-4 Unit Rentals | Stonehaven",
 desc="What changes when the rental has several units: rent-roll review, unit legality, occupancy and property-type checks for two-to-four-unit DSCR files.",
 h1="Several rents. One financing decision",
 sub="A small multifamily property multiplies the rents and the review points. This page covers what the extra units add to the file.",
 answer="Two-to-four-unit properties can finance under residential DSCR programs: the units' combined eligible rent is sized against the property's qualifying payment (PITIA). The relevant limitation: every unit must survive review, meaning legal status, condition and rent evidence per unit, and this page addresses investment financing, not owner-occupied multifamily purchases, which follow different rules elsewhere.",
 scen_h="An illustrative triplex review",
 scen=["A buyer evaluates a triplex where two units hold long leases and the third was converted by a prior owner. If the third unit's legal status cannot be verified, programs may not count its rent, and the deal's math changes immediately. Illustrative example, not a customer.",
      "The rent roll is the headline; the units' paperwork is the story underneath it."],
 fit_h="Small multifamily against single-family, for financing purposes",
 fit=["More units mean more rent lines supporting one payment, which can stabilize the ratio against a single vacancy. They also mean more review surface: per-unit legality, per-unit condition, per-unit evidence. The financing product is the same family; the file is denser.",
      "At five or more units the property leaves residential classification entirely and routes to commercial analysis. If your growth plan crosses that line, see the portfolio page for the routing."],
 module=dict(type="checklist", h="Rent-roll and unit review list",
  intro="The per-unit file, assembled before underwriting asks:",
  items=[("Rent roll, current and complete","Every unit: rent, lease term, deposit, tenancy start. Blanks read as findings."),
         ("Unit legality","Permits or records for each unit, especially any converted or added space. Non-conforming units may not count."),
         ("Occupancy status","Which units are occupied, at what rent, on what paper; vacant units invoke program-specific market-rent treatment."),
         ("Per-unit condition","Deferred maintenance in one unit affects the whole property's appraisal and eligibility."),
         ("Meters, utilities and access","Separate metering and lawful unit access are appraisal-visible facts worth knowing early.")]),
 qual=["Combined eligible rent across counted units",
       "Legal status of every unit",
       "Property condition and appraisal results",
       "Occupancy mix and rent evidence per unit",
       "Credit, leverage and reserves as everywhere"],
 obj=[("One unit is vacant; does the deal die?","Not necessarily: programs apply defined treatments for vacant units, often the appraiser's market rent, with variations for purchase versus refinance. The mix is reviewed rather than assumed either way."),
      ("The basement unit has no permit but always rents.","Then its rent may not count and its presence may raise condition and legality questions. Better to price the property on its counted units and treat extra income as unfinanced upside.")],
 faqs=[("Is a duplex financed like a single-family rental?","Same product family with a denser file: combined rent across units against the property's payment, plus per-unit legality and condition review. See also the first-time investor page if this is your first purchase."),
       ("Can I live in one unit and rent the rest under these programs?","This page covers investment financing; owner-occupied multifamily purchases follow different programs and rules and are not promised here. Be precise about occupancy plans in review."),
       ("How is vacant-unit rent counted?","Per program rules, commonly at the appraiser's market rent with defined haircuts or conditions, and treatment can differ between purchase and refinance. The exact rule is confirmed per program."),
       ("Does mixed occupancy (one lease, one month-to-month) matter?","It shapes evidence quality per unit and how programs weigh lease versus market figures. Bring the full picture; partial rent rolls stall files."),
       ("What happens above four units?","Residential DSCR classification ends; commercial analysis begins, with income assessed as NOI against annual debt service. Stonehaven routes those scenarios to commercial review.")],
 related=["first-time-investors","long-term-rentals","portfolio-growth"]),

dict(id="DSCR-LP015", slug="cash-purchase-refinance", label="Cash buyers refinancing",
 angles=["DSCR-A009"], index=True,
 query="delayed financing cash purchase refinance rental",
 title="Bought With Cash? The Refinance Review | Stonehaven",
 desc="What to check before refinancing a cash acquisition: purchase documentation, ownership timing, valuation basis and how refinance structures differ.",
 h1="Bought with cash? Review what comes next",
 sub="Cash won the deal. The refinance decides how much of that cash goes back to work, and its rules reward buyers who kept clean records.",
 answer="Refinancing a cash purchase returns leverage to a property bought outright. Programs classify these scenarios under specific rules: how recently you bought, how the purchase is documented, and whether the transaction is treated under delayed-financing-style provisions or standard cash-out rules, which carry different limits and valuation treatment. The relevant limitation: timing and documentation, not the purchase price, decide what a refinance can return, and full recovery of the invested cash is not promised.",
 scen_h="An illustrative post-cash refinance",
 scen=["An investor closed a $200,000 cash purchase two months ago, spent $20,000 on improvements, and wants capital back for the next deal. Whether the file runs under delayed-financing-style treatment or waits for standard cash-out seasoning, and whether valuation uses cost or current appraisal, are rules questions with materially different answers. Illustrative example, not a customer.",
      "Both paths exist in the market; which applies is a program fact, not a preference."],
 fit_h="Refinance now, later, or not at all",
 fit=["An early refinance restores liquidity for the next purchase at the cost of a payment on this one. Waiting can change the valuation basis and the applicable rules. Not refinancing keeps the property unlevered, which for some hold plans is exactly right.",
      "The comparison is the released capital's next use against the new payment and costs here, run at the leverage the applicable classification actually permits."],
 module=dict(type="checklist", h="The cash-purchase paper trail",
  intro="Documents that decide how favorably the refinance classifies, gathered from day one:",
  items=[("Closing statement","The settlement statement proving the cash purchase: price, date, and that no financing was recorded."),
         ("Source-of-funds records","Documentation of the cash used, as programs may verify the purchase money's path."),
         ("Title and vesting history","Clean chain since purchase; any transfer since closing complicates seasoning review."),
         ("Improvement records","Invoices and scope for post-purchase work, supporting the valuation story."),
         ("The calendar","Purchase date against today's date: classification and valuation rules key on the interval.")]),
 qual=["Ownership-time rules and refinance classification",
       "Valuation basis: purchase price versus current appraisal, per rules and timing",
       "Documented purchase and funds trail",
       "Eligible rent and the property's numbers, as everywhere",
       "Credit, leverage and reserves"],
 obj=[("I paid cash precisely to avoid loan hoops; now more hoops?","The refinance is a new loan, so its checks apply; the cash purchase changed the sequence, not the standards. What cash did buy is a stronger negotiating position then and classification options now."),
      ("Can I count my renovation in the value?","Documented improvements support the appraisal narrative; whether current value or cost basis governs depends on classification and timing rules. Undocumented work supports nothing.")],
 faqs=[("How soon after a cash purchase can I refinance?","Sooner than many expect under delayed-financing-style provisions, later under standard cash-out seasoning; the classification depends on documentation and program rules. The review establishes which path your dates and papers support."),
       ("Will the refinance use my purchase price or the new appraisal?","Classification and timing decide the valuation basis, and programs differ. This is the single biggest driver of proceeds on recent purchases, which is why the review pins it first."),
       ("Do I need the property rented first?","Rent evidence rules apply as in any DSCR file: a lease strengthens it; rent-ready market-rent treatment may be considered per program. Sequencing rent-up and refinance is part of the plan."),
       ("Is this the same as a BRRRR refinance?","They rhyme: BRRRR adds a rehab stage and its valuation story. This page covers the acquisition-history and classification questions; the BRRRR page covers the project sequence."),
       ("What kills these files most often?","Missing settlement statements, undocumented funds, and title moves after closing. All preventable with the checklist above, none fixable retroactively.")],
 related=["brrrr-refinance","cash-out-refinance","bridge-loan-refinance"]),

dict(id="DSCR-LP016", slug="hold-or-sell", label="Hold-or-sell decisions",
 angles=["DSCR-A016"], index=True,
 query="refinance or sell rental property decision",
 title="Hold or Sell the Rental: Match the Financing | Stonehaven",
 desc="How financing fits the intended holding period: a hold-versus-exit comparison with costs and prepayment exposure, without individualized tax conclusions.",
 h1="Match the financing to the hold plan",
 sub="Financing chosen without an exit horizon is a guess wearing paperwork. This page puts the hold decision and the loan decision in the same frame.",
 answer="Whether to hold a rental with new financing or sell it is a comparison of two complete pictures: the hold's economics at the proposed payment over your realistic horizon, against the sale's net after costs today. The relevant limitation, twice over: prepayment terms can charge for changing your mind, and nothing here is individualized tax advice; sale and hold both carry tax consequences that belong with your tax adviser.",
 scen_h="An illustrative fork",
 scen=["An owner five years into a rental weighs refinancing for a longer hold against selling into a favorable market. Refinance costs plus a possible prepayment structure argue for certainty about the horizon; selling crystallizes today's equity minus transaction costs. Choosing the refinance and selling in year two would pay for both decisions. Illustrative example, not a customer.",
      "The expensive outcome is not choosing wrong; it is paying entry costs for one plan and exit costs for another."],
 fit_h="What financing has to do with the answer",
 fit=["Financing does not decide hold-or-sell; it prices the hold branch. A structure with heavy prepayment exposure suits a confident long hold and punishes a wavering one; lighter prepayment structures may cost more monthly and buy flexibility.",
      "If the honest horizon is short or uncertain, the right financing may be none, and the right page may be the sale conversation with your agent instead."],
 module=dict(type="table", h="Hold against sell, in one frame",
  intro="The two branches, itemized honestly. Illustrative structure; your numbers complete it:",
  cols=("Component","Hold with new financing","Sell now"),
  items=[("Upfront costs","Refinance closing costs","Sale costs: commission, concessions, closing"),
         ("Ongoing picture","Rent minus new PITIA minus operations","None; capital released"),
         ("Capital position","Equity stays in, possibly some released","Net proceeds after costs and payoff"),
         ("Flexibility cost","Prepayment terms if plans change","Decision is final on closing"),
         ("Horizon it rewards","The full intended hold","Today"),
         ("Tax dimension","Exists; see your tax adviser","Exists; see your tax adviser")]),
 qual=["Prepayment structure of any proposed financing",
       "Eligible rent and payment for the hold branch",
       "Realistic transaction costs for the sale branch",
       "Your actual horizon confidence, stated honestly",
       "Credit, leverage and reserves for any refinance"],
 obj=[("Can you tell me whether to sell?","No, and distrust any lender page that does. What a review can do is price the hold branch precisely so your comparison uses real numbers on both sides."),
      ("What about taxes on the sale?","Material, individualized and outside this page's lane. Bring your tax adviser the same two-branch frame; the decision deserves both inputs.")],
 faqs=[("How do prepayment terms change the decision?","They price flexibility: heavier structures can cost real money on an early exit, so they suit confident holds. Ask for the exact structure and model your realistic wobble, not your hoped-for discipline."),
       ("Is refinancing before selling ever rational?","Occasionally, for defined bridging reasons, but paying entry costs shortly before exit costs needs a specific justification. The frame above exposes whether one exists."),
       ("What horizon should I use in the comparison?","The one you would bet on, not the one that flatters the math. If the honest answer is a range, run the comparison at both ends and see which branch survives."),
       ("Does holding always beat selling long-term?","No general answer exists; it depends on the property's economics at the new payment, the market, and your alternatives for the capital. That is why this is a comparison page, not a recommendation page."),
       ("Who should be in this decision besides a lender?","Your tax adviser for the tax dimension and, for the sale branch, an agent's real market read. Financing review covers one branch well; the decision uses all three inputs.")],
 related=["rate-and-term-refinance","cash-out-refinance","long-term-rentals"]),

dict(id="DSCR-LP017", slug="veteran-investors", label="Veteran investors",
 angles=["DSCR-A026"], index=True,
 query="can veterans use va loan for rental property dscr alternative",
 title="Veterans Financing a Rental: VA vs DSCR Facts | Stonehaven",
 desc="How financing a dedicated rental differs from a qualifying owner-occupied VA purchase: the accurate distinction, a rental scenario and a neutral comparison.",
 h1="For veterans exploring a rental investment: start with the deal",
 sub="Two different questions get mixed together constantly: what VA home-loan benefits cover, and how a dedicated rental investment gets financed. This page keeps them straight.",
 answer="VA purchase financing is intended for a qualifying primary residence, not a dedicated rental investment purchase. A veteran buying a property purely as a rental finances it the way any investor does, including DSCR programs sized on eligible rent against the qualifying payment (PITIA). The relevant limitation, stated plainly: DSCR is not a VA benefit, carries no government backing, and no veteran-specific DSCR advantage exists here. This page exists because the accurate distinction is genuinely useful, not because service status changes terms.",
 scen_h="An illustrative pair of situations",
 scen=["Situation one: a veteran uses VA financing to buy a primary residence, lives there, and later converts it to a rental after moving; the former primary becoming a rental is a recognized, different situation with its own rules. Situation two: the same veteran buys a second property purely as an investment; VA purchase financing is not the tool for that, and investment financing paths apply. Illustrative situations, not customers.",
      "Most confusion online comes from blending these two. Keeping them separate makes both decisions cleaner."],
 fit_h="A neutral comparison for the dedicated rental",
 fit=["For the investment purchase, the comparison is the standard one: conventional investment financing using documented income against DSCR structures sized on the property's rent, judged on total cost, reserves and program rules for your file.",
      "Service history does not move those numbers in either direction on this page, and any page implying a veteran DSCR discount or government endorsement is selling something other than accuracy."],
 module=dict(type="table", h="Owner-occupied VA purchase versus investment financing",
  intro="The accurate distinction, side by side:",
  cols=("Question","VA purchase financing","Investment financing (incl. DSCR)"),
  items=[("Intended use","Qualifying primary residence occupancy","A property held as an investment"),
         ("Buying a dedicated rental","Not the intended tool","The applicable category"),
         ("Government backing","VA guaranty per program rules","None; private programs"),
         ("Income assessed","Borrower qualification per VA rules","Property's eligible rent against PITIA under DSCR; borrower income under conventional"),
         ("Former primary later rented","A recognized separate situation with its own rules","Not this column's question"),
         ("Veteran-specific advantage","Defined VA benefits for eligible use","None represented here")]),
 qual=["The property's eligible rent and payment, as for any investor",
       "Credit, leverage and reserves",
       "Property type, condition and state availability",
       "Ownership structure if using an entity"],
 obj=[("Shouldn't my service earn better terms somewhere?","On VA-eligible owner-occupied purchases, defined benefits exist and are worth using properly. On a dedicated rental investment, no veteran-specific advantage is offered here, and we would rather say that than imply one."),
      ("I keep seeing 'VA investment loans' advertised.","Read them carefully: they usually describe multi-unit owner-occupied purchases with rental units, or former primaries later rented. A property bought purely as a rental is a different transaction, which is this page's whole point.")],
 faqs=[("Can I buy a rental property with a VA loan?","VA purchase financing is intended for a qualifying primary residence. Certain owner-occupied multi-unit purchases include rental units under VA occupancy rules, and a former primary can later become a rental; a dedicated rental purchase is a different transaction financed through investment paths."),
       ("Is there a veteran discount on DSCR loans?","No veteran-specific DSCR benefit is represented here. Terms follow the property, credit, leverage and program, and pages claiming otherwise deserve skepticism."),
       ("I rented out my old VA-financed home; does that affect a new purchase?","Prior use and entitlement questions belong with VA-loan specialists under VA rules. This page's scope is the dedicated rental investment; bring the full history to whichever review you start."),
       ("Does military income count differently for investment financing?","Under DSCR programs the qualification centers on the property's rent; under conventional paths, documented income including military income is assessed per those rules. Nothing special or worse attaches to its source."),
       ("Why does this page exist if veterans get no special terms?","Because the VA-versus-investment distinction is the single most misexplained topic aimed at veteran investors, and an accurate explanation is worth a page even when its conclusion is 'the standard rules apply.'")],
 related=["first-time-investors","experienced-landlords","working-professionals"]),
]
