# -*- coding: utf-8 -*-
"""DSCR persona LP content, part A (LP001-LP009). Source: Stonehaven DSCR
Audience and Creative Strategy v1 (9 Sep 2026) + the page register.
Edit copy here, then: python3 scripts/build-dscr-personas.py
Module types: checklist, timeline, table (rows of [label, a, b]), twocol.
All claims conditional scenario-review language per the strategy claim rules."""

PAGES_A = [
dict(id="DSCR-LP001", slug="experienced-landlords", label="Experienced landlords",
 angles=["DSCR-A001","DSCR-A018","DSCR-A019","DSCR-A020"], index=True,
 query="dscr loan for next rental property purchase",
 title="DSCR for Your Next Rental Purchase | Stonehaven",
 desc="How experienced landlords can evaluate DSCR financing for the next rental: rent sensitivity, taxes, insurance, cash to close and reserves, compared honestly.",
 h1="The next rental deserves its own financing review",
 sub="You have bought before. This page is the disciplined way to compare financing for the next one: the property's numbers first, the loan structures second.",
 answer="A DSCR review assesses the property's eligible rental income against the qualifying monthly payment (principal, interest, taxes, insurance and association dues, together called PITIA). It is one financing path among several for an experienced buyer; conventional investment loans also recognize rental income. The relevant limitation: a passing ratio does not establish approval or a sound investment, and credit, leverage, reserves and property condition still matter.",
 scen_h="An illustrative next-purchase decision",
 scen=["A landlord with three paid-down rentals is weighing a fourth at a $340,000 asking price with $2,600 expected market rent. The question is not whether financing exists; it is which structure carries the deal best once taxes, insurance and the down payment are counted honestly. This example is illustrative, not a customer or a closed loan.",
       "Run the numbers both ways before choosing: what the payment looks like under a DSCR program sized on the property's rent, and what a conventional investment loan looks like using personal income plus rental credit. The cheaper full structure wins, not the more familiar one."],
 fit_h="Where DSCR fits, and where it may not",
 fit=["DSCR can suit a buyer whose portfolio or tax position makes property-based underwriting simpler than documenting personal income across several schedules. Conventional financing can win on total cost for strong personal-income files, and a local bank relationship can win on flexibility.",
      "The comparison worth making covers total cost, reserves required, property rules and prepayment terms. If conventional pricing beats the DSCR structure for your file, that is the answer a review should give you."],
 module=dict(type="checklist", h="Sensitivity checklist before you offer",
  intro="Five numbers move a next-purchase decision more than the asking price. Check each before committing financing assumptions:",
  items=[("Rent, tested lower","What happens to the ratio and your cash flow if the appraiser's market rent lands 10% under your estimate? The appraisal number, not your projection, is what a lender uses."),
         ("Property taxes, next year's","Taxes often reset on sale. Qualify the deal on the post-purchase tax bill, not the seller's current one."),
         ("Insurance, quoted not assumed","Premiums vary sharply by state and construction. Get a real quote into the payment before you compare loans."),
         ("Cash to close, all of it","Down payment plus closing costs plus any lender-required reserves. The down payment alone understates the check you write."),
         ("Reserves after closing","Many programs expect months of payments in liquid reserve after funding. Count what remains, not what you start with.")]),
 qual=["Eligible rent treatment (lease versus appraiser market rent) varies by program",
       "Credit profile and mortgage history affect eligibility and leverage",
       "Loan-to-value limits set the down payment floor",
       "Liquid reserves after closing are commonly required",
       "Property type, condition and location rules apply",
       "Experience can affect terms under some programs"],
 obj=[("It probably costs more than my last conventional loan.","Sometimes it does. The honest comparison is total cost against what your file qualifies for conventionally today, including reserve and documentation differences. A review puts both on paper; if conventional wins, that is the recommendation."),
      ("The appraisal rent might come in low.","It might, and it controls. Test the deal at a lower rent before you offer, and keep a plan for the gap: more down, a different structure, or walking away.")],
 faqs=[("Do experienced landlords get better DSCR terms?","Under some programs, experience can affect eligibility or terms, but it is one factor among credit, leverage, reserves and the property itself. No program rewards experience with automatic approval."),
       ("Can I use a DSCR loan and conventional loans across the same portfolio?","Commonly, yes. Many investors mix structures property by property. Which loan belongs on which property depends on each deal's numbers and each program's rules."),
       ("What rent figure will the lender actually use?","Typically the lower of the lease or the appraiser's market-rent finding, with program-specific variations. Your projection is a planning number, not an underwriting number."),
       ("How many financed properties can I have?","Limits vary by program. Conventional lending applies defined property-count rules; DSCR programs set their own. A review checks your count against the programs actually available."),
       ("Does the review commit me to a DSCR loan?","No. The review compares paths, including conventional and bank options, and can conclude a different structure fits better.")],
 related=["portfolio-growth","long-term-rentals","rate-and-term-refinance"]),

dict(id="DSCR-LP002", slug="bridge-loan-refinance", label="Bridge and hard-money refinance",
 angles=["DSCR-A011","DSCR-A013","DSCR-A014"], index=True,
 query="refinance hard money loan to dscr rental loan",
 title="Refinance a Bridge or Hard-Money Loan to DSCR | Stonehaven",
 desc="Is the property ready for rental takeout? Payoff and maturity planning, property readiness, rent evidence and refinance cost review for bridge borrowers.",
 h1="The rehab is finished. Review the financing for the hold",
 sub="Short-term money did its job. This page is about whether the property, the timeline and the numbers are ready for longer-term rental financing.",
 answer="A takeout refinance replaces bridge or hard-money debt with longer-term financing sized on the property's eligible rent against its qualifying payment (PITIA). The relevant limitation: completion alone is not readiness. Condition, ownership timing, rent evidence, valuation and payoff economics all decide whether a takeout works now, later, or not on these terms.",
 scen_h="An illustrative takeout decision",
 scen=["An investor holds a renovated single-family rental on a 12-month bridge note maturing in four months. The unit leased two months ago. The live questions: does the seasoning clock fit the maturity date, will the new appraisal support the payoff, and does the takeout payment leave the rental cash-flowing? Illustrative example, not a customer.",
      "The wrong move is waiting until maturity forces the timing. Takeout review should start while there is calendar room to fix what underwriting finds."],
 fit_h="Takeout, extension, or sale",
 fit=["A DSCR takeout suits a stabilized, leased property the investor intends to hold. If the property is unfinished or unleased, a bridge extension or a different completion plan may fit better. If the plan was always to sell, refinance costs may be money spent against the wrong exit.",
      "The comparison covers the full refinance cost, the payoff amount including any bridge exit fees, and what the new payment does to the hold economics."],
 module=dict(type="timeline", h="Readiness timeline for a rental takeout",
  intro="Work backward from the bridge maturity date. Each checkpoint has to clear before the next matters:",
  items=[("Months out: 4+","Property complete and rent-ready. Punch-list items closed; condition issues that appraisers flag are resolved."),
         ("Months out: 3","Lease signed or listing active. Programs differ on accepting a new lease versus market rent; in-place rent evidence strengthens the file."),
         ("Months out: 2-3","Ownership and seasoning check. Time-owned requirements and valuation basis (purchase plus documented rehab versus current appraisal) vary by program and affect proceeds."),
         ("Months out: 2","Payoff quote from the bridge lender, including exit fees and per-diem interest. The takeout must cover the real number, not the balance you remember."),
         ("Months out: 1-2","Full application, appraisal and underwriting. Leave room for conditions; a maturity date is not a closing guarantee.")]),
 qual=["Time owned and valuation basis rules affect proceeds",
       "Rent evidence requirements (lease, receipts, market rent) vary by program",
       "Property condition must support the appraisal",
       "Payoff amount, exit fees and closing costs decide the economics",
       "Credit, reserves and leverage limits still apply"],
 obj=[("My bridge matures before a refinance could close.","Then the sequencing conversation matters more than the product conversation: what an extension costs, what a realistic takeout timeline is, and which starts first. No one should promise a closing date to solve a maturity problem."),
      ("Will I recover my full rehab spend?","Not necessarily. Proceeds depend on the appraisal, program leverage limits and seasoning rules, not on what the project cost. A review estimates the realistic range before you count on the capital.")],
 faqs=[("How soon after buying can I refinance out of hard money?","Ownership-time and valuation rules vary by program: some consider current value quickly, others apply seasoning before full appraised value is used. The review checks your dates against actual program rules."),
       ("Does the property need a tenant before takeout?","Programs differ. A signed lease strengthens most files; some accept the appraiser's market rent for a rent-ready vacant unit. Which applies is a program fact worth confirming before planning."),
       ("What if the appraisal comes in under my payoff?","Then the structure needs rework: more cash in, a different program, an extension, or a sale. Better to test that scenario months out than at maturity."),
       ("Do bridge exit fees change the decision?","They can. Exit fees and per-diem interest belong in the payoff figure, and the full refinance cost belongs in the comparison against extending or selling."),
       ("Is a takeout guaranteed if the ratio passes?","No. The ratio is one input; condition, seasoning, credit, reserves and valuation all still decide.")],
 related=["brrrr-refinance","cash-purchase-refinance","long-term-rentals"]),

dict(id="DSCR-LP003", slug="cash-out-refinance", label="Rental cash-out refinance",
 angles=["DSCR-A007","DSCR-A008","DSCR-A010","DSCR-A029"], index=True,
 query="dscr cash out refinance rental property",
 title="Rental Cash-Out Refinance, Reviewed Honestly | Stonehaven",
 desc="What changes if you refinance to access rental equity: current-loan versus refinance economics, net-proceeds components, and what the rental must still support.",
 h1="Before the next purchase, review the equity math",
 sub="A cash-out refinance can release eligible investment-property equity. It also replaces the loan you have. Both halves belong on the same page of paper.",
 answer="A rental cash-out refinance replaces the current loan with a larger one and returns the difference, less costs, as proceeds. Eligibility is assessed on the property's rent against the new qualifying payment (PITIA), plus credit, seasoning, leverage and reserves. The relevant limitation: the refinanced rental must still work as an investment at the new payment, and replacing existing debt changes its economics. This is not the HELOC situation; the existing loan does not stay in place.",
 scen_h="An illustrative equity decision",
 scen=["An owner holds a rental worth about $400,000 with a $210,000 balance and wants capital for another purchase. The gross gap is $190,000; the usable number is smaller after program leverage limits, closing costs and any reserve requirements, and the new payment is larger for as long as the loan runs. Illustrative example, not a customer.",
      "The decision is whether the next investment earns more than the refinance costs, on both properties, at the same time."],
 fit_h="Cash-out against the alternatives",
 fit=["Compare three paths honestly: keep the current loan and fund the next purchase another way, take the cash-out and accept the new payment, or use an available second-lien structure if one exists for the scenario. Each has a different cost and a different effect on the existing rental.",
      "If the current loan carries terms worth keeping and the new blended cost is high, keeping it can be the right answer. The review should be willing to say so."],
 module=dict(type="table", h="Current loan versus proposed refinance, side by side",
  intro="The comparison that decides this is a two-column exercise. Illustrative structure; your review fills in real numbers:",
  cols=("What to compare","Current loan","Proposed cash-out"),
  items=[("Monthly payment (PITIA)","Known today","Larger; sized at the new balance"),
         ("Remaining term","Whatever remains","Resets per the new note"),
         ("Net proceeds","None","New loan minus payoff, closing costs and any required reserves"),
         ("Rental's monthly margin","Current rent minus current payment","Same rent minus the larger payment"),
         ("Prepayment exposure","Per existing note","New prepayment terms apply"),
         ("Effect on next purchase","Capital found elsewhere","Capital in hand, at the cost above")]),
 qual=["Seasoning and prior-financing history affect eligibility and valuation basis",
       "Program leverage limits for cash-out are typically tighter than purchase limits",
       "The property must support the new payment at eligible rent",
       "Proceeds-use questions are part of many program reviews",
       "Credit, reserves and property condition still apply"],
 obj=[("How much will I actually clear?","Net proceeds are the loan amount minus payoff, costs and any required reserves. A review itemizes the components rather than quoting the gross equity gap, because the gross gap is never the check."),
      ("Does this hurt the rental I already own?","It changes it: same rent, larger payment, new term, new prepayment terms. Whether that trade is worth it depends on what the released capital earns. That comparison is the review.")],
 faqs=[("How long must I have owned the rental before a cash-out?","Seasoning rules vary by program, and prior cash-out timing can matter too. Your ownership dates get checked against actual program rules during review."),
       ("Is there a limit on cash-out proceeds?","Programs set leverage limits, often tighter for cash-out than for purchases, and the property's appraisal controls the base. The usable number comes from the review, not a rule of thumb."),
       ("Can proceeds fund another rental purchase?","Funding another investment is a common use; programs may ask about intended use as part of review. What no program does is guarantee proceeds in advance."),
       ("Would a second lien beat a full refinance?","Sometimes, when the current first-lien terms are worth keeping and a suitable second-lien structure exists for investment property. Availability is scenario-specific; the review compares whichever paths actually exist for your file."),
       ("Does the old loan stay in place?","No. A cash-out refinance pays off and replaces the existing loan. Keeping the current loan is only possible under the keep-or-second-lien paths, where available.")],
 related=["rate-and-term-refinance","cash-purchase-refinance","hold-or-sell"]),

dict(id="DSCR-LP004", slug="self-employed-investors", label="Self-employed investors",
 angles=["DSCR-A003"], index=True,
 query="dscr loan for self employed real estate investor",
 title="DSCR for Self-Employed Rental Investors | Stonehaven",
 desc="How property-based underwriting compares with personal-income paths for self-employed rental buyers: what is documented, what still matters, what to compare.",
 h1="Start the rental-loan conversation with the property",
 sub="Self-employed income is real income; it is just documented differently. A property-based underwriting path can simplify one part of the file. It removes none of the others.",
 answer="DSCR programs assess the rental's eligible income against the qualifying payment (PITIA) instead of underwriting personal income the conventional way. For a self-employed buyer, that can mean the rental review does not run through business tax schedules. The relevant limitation: this is not a no-documentation loan. Credit, assets, reserves, the property and ownership are still documented and still decide.",
 scen_h="An illustrative comparison",
 scen=["A business owner with strong cash flow and a tax return optimized for the business is buying a $300,000 rental expected to bring $2,400 rent. Conventionally, qualification runs through personal income as filed. Under a DSCR program, qualification centers on the property's numbers, with the borrower's credit, assets and history still reviewed. Illustrative example, not a customer.",
      "Neither path is automatically better. The one that wins is the one whose full cost and requirements fit this file, and that is knowable before applying anywhere."],
 fit_h="When property-based underwriting helps, and when it does not",
 fit=["It helps when documenting personal income is the slow or distorting part of the file: complex schedules, recent structural changes, income that is real but reads oddly on paper. It does not help when conventional pricing for your file beats the DSCR structure, which happens regularly for strong filers.",
      "Conventional lending also recognizes rental income, so do not assume rejection anywhere. Compare, then choose."],
 module=dict(type="table", h="What gets documented, path by path",
  intro="A documentation comparison, stated plainly. Neither column is 'no documents':",
  cols=("Item","Property-based (DSCR) path","Personal-income path"),
  items=[("Personal or business tax returns","Commonly not the qualification basis","Central to qualification"),
         ("Property rent evidence","Central: lease and appraiser market rent","Considered under rental-income rules"),
         ("Credit report and history","Reviewed; affects eligibility and leverage","Reviewed"),
         ("Assets and reserves","Documented; reserves commonly required","Documented"),
         ("Entity documents (if vesting in an LLC)","Reviewed where permitted","Varies by program"),
         ("Appraisal with rent analysis","Required","Appraisal required; rent analysis when using rental income")]),
 qual=["Credit profile and mortgage history",
       "Down payment and program leverage limits",
       "Liquid reserves after closing",
       "Property type, condition and appraisal results",
       "Ownership structure and guarantor requirements where entities are used"],
 obj=[("Is this just a more expensive workaround?","It can cost more than conventional financing for the same file, and a fair review says so when true. The value is fit: for some self-employed files the property-based path is cleaner and worth its price; for others it is not."),
      ("Do I avoid paperwork entirely?","No. You avoid one category of documentation. Credit, assets, entity papers and the property file remain, and the strategy words it plainly: no program here is a no-documentation program.")],
 faqs=[("Do DSCR lenders look at my tax returns at all?","Under many programs, personal income tax documentation is not the qualification basis for the loan. Program specifics vary, and other financial documentation is still collected."),
       ("Does being self-employed qualify me for DSCR?","No occupation qualifies anyone. The property's numbers, your credit, assets and the program's rules decide. Self-employment just changes which path is more convenient to document."),
       ("Can my LLC hold the property?","Entity vesting is permitted under some programs, typically with personal guaranties and entity documentation. See the LLC ownership page for the specifics worth preparing."),
       ("Will conventional financing reject me anyway?","Do not assume that. Conventional programs recognize self-employed income under their rules, and for many files they price well. The point of a review is comparing, not presuming."),
       ("What should I bring to a preliminary review?","The property numbers (price, expected rent, taxes, insurance), your rough credit picture, available cash, and how you plan to hold title. Rough numbers are fine to start.")],
 related=["llc-investors","working-professionals","experienced-landlords"]),

dict(id="DSCR-LP005", slug="first-time-investors", label="First-time rental investors",
 angles=["DSCR-A002"], index=True,
 query="first rental property loan requirements dscr",
 title="First Rental Property: DSCR and the Numbers | Stonehaven",
 desc="What a first-time rental investor must understand before financing: cash needs, reserves, program experience rules, and how first-timer definitions differ.",
 h1="First rental? Start with the numbers",
 sub="The first investment property brings questions the first home never asked. This page walks the financing side in order, before anyone fills in a form.",
 answer="A first rental purchase can be financed through several paths, including DSCR programs where experience rules allow and conventional investment loans. The two facts to hold onto: first-time investor and first-time homebuyer are different definitions with different program treatment, and cash requirements (down payment plus closing costs plus reserves) are larger than most first-time buyers expect. Program experience restrictions exist; some programs limit or overlay terms for inexperienced borrowers.",
 scen_h="An illustrative first purchase",
 scen=["A renter-by-choice who owns no property wants a $250,000 duplex as a first investment. Some programs treat a first-time homebuyer differently from an experienced homeowner buying a first rental, and the two cases may see different eligibility. The cash need spans down payment, closing costs and commonly months of reserves. Illustrative example, not a customer.",
      "The right first step is a review that names which definitions apply to you and which programs actually consider your case, before any application."],
 fit_h="DSCR against conventional for a first purchase",
 fit=["Conventional investment financing is often the natural first comparison for a first-timer with documentable income, and it can price well. DSCR paths matter where personal-income documentation is the obstacle or where the program's treatment of the property's rent helps the structure.",
      "Where novice overlays or first-time homebuyer exclusions apply, the review's job is finding the path that considers your case, and being honest if the better move is waiting or buying differently."],
 module=dict(type="checklist", h="Before you finance a first rental",
  intro="Five things to understand in order, each one before the next:",
  items=[("Which 'first-time' you are","First-time homebuyer (never owned a home) and first-time investor (own a home, first rental) are treated differently by programs. Know which case you present."),
         ("The full cash requirement","Down payment, closing costs, and commonly several months of PITIA in reserve. Total it before falling for a listing."),
         ("The rent a lender counts","The appraiser's market-rent analysis or a lease, per program rules; not the listing agent's projection."),
         ("Your credit position","Credit affects eligibility and leverage everywhere. Know the picture before underwriting tells you."),
         ("The operating reality","Vacancy, repairs and management come out of the rent that a qualification ratio does not model. Lender DSCR is not your cash flow.")]),
 qual=["Experience and first-time definitions under each program",
       "Credit and any program overlays for newer borrowers",
       "Down payment and leverage limits, often more conservative for first-timers",
       "Reserves after closing",
       "Property type and condition rules"],
 obj=[("Do I need to own a home first?","Some programs restrict borrowers who have never owned property; others consider certain first-time homebuyer cases with overlays. The definitions differ by program, which is exactly why the review starts with them."),
      ("Is the down payment really that large?","Investment leverage limits are more conservative than owner-occupied lending, and reserves add to the cash need. The honest total is the one to plan on; the review computes it.")],
 faqs=[("Can a first-time homebuyer get a DSCR loan?","Program-dependent. Some exclude first-time homebuyers from DSCR programs; others consider them with overlays. This is a definition-and-program question a review answers for your specific case."),
       ("How much cash does a first rental take?","Plan on the down payment under investment leverage limits, closing costs, and commonly months of reserves. The exact figure depends on program and property; the shape of the answer does not."),
       ("Is a duplex a good first rental for financing purposes?","Two-to-four-unit properties are financeable under residential programs with additional review of rent rolls and unit legality. See the 2-4 unit page for the specifics."),
       ("Will the lender teach me what to do?","A lender underwrites; it does not manage the property. Budget for management or self-manage deliberately. Qualification and operating success are different problems."),
       ("What if the review says I am not ready?","Then you learned it before spending on applications and appraisals. A review that can say 'not yet, and here is what changes it' is the useful kind.")],
 related=["long-term-rentals","2-4-unit-properties","working-professionals"]),

dict(id="DSCR-LP006", slug="brrrr-refinance", label="BRRRR refinance planning",
 angles=["DSCR-A012"], index=True,
 query="brrrr refinance dscr seasoning requirements",
 title="Planning the BRRRR Refinance Stage | Stonehaven",
 desc="How to plan the refinance stage across a BRRRR project: purchase, rehab, rent-up and refinance timeline with seasoning and valuation checkpoints.",
 h1="The refinance deserves a plan of its own",
 sub="Buy, rehab, rent, refinance, repeat works only as well as its third and fourth steps. This page plans the refinance from the day you buy, not the day the paint dries.",
 answer="In a BRRRR sequence, the refinance converts short-term capital into long-term rental financing, ideally recovering much of the invested cash. Eligibility runs on the property's eligible rent against the new qualifying payment (PITIA), plus seasoning and valuation rules that decide when and on what value basis the refinance can happen. The relevant limitation: proceeds depend on the appraisal, program leverage limits and timing rules, not on what the project cost, and full capital recovery is never guaranteed.",
 scen_h="An illustrative BRRRR timeline decision",
 scen=["An investor buys a dated property for $180,000, budgets $45,000 of rehab, and projects a $290,000 stabilized value with $2,200 rent. Whether the refinance returns most of the $225,000 basis depends on the appraisal, the program's leverage limit, and whether seasoning rules let the new value count when the refinance is needed. Illustrative example, not a customer.",
      "Planned early, a weak link in that chain changes the purchase decision. Discovered late, it strands capital."],
 fit_h="Where the BRRRR refinance differs from a bridge takeout",
 fit=["A bridge takeout asks: is this property ready to replace maturing short-term debt? The BRRRR refinance asks a planning question across the whole sequence: when should the refinance happen, on what valuation basis, and what does the answer do to the capital plan for the next deal.",
      "If the timeline and valuation rules will not support the recovery you need, the options are adjusting the buy price, the rehab scope, the hold plan, or the financing sequence. All easier before closing than after."],
 module=dict(type="timeline", h="The four stages, with financing checkpoints",
  intro="Each stage sets up the refinance. Test the plan at every checkpoint:",
  items=[("Buy","Underwrite the exit at purchase: projected stabilized value, projected rent, and the program leverage that would apply. If the numbers only work at optimistic values, they do not work."),
         ("Rehab","Document everything: scope, invoices, permits where required. Documented rehab supports the valuation story and some programs' value treatment."),
         ("Rent","A signed lease at a market-supported rent is the strongest evidence; rent-ready with market rent may be considered per program. The rent figure drives the ratio the refinance is sized on."),
         ("Refinance","Check seasoning against the calendar: programs differ on when current appraised value counts versus cost basis. Then size proceeds honestly: appraisal times program leverage, minus payoff and costs.")]),
 qual=["Seasoning rules and valuation basis (cost versus current appraisal) by program",
       "Eligible rent evidence at the time of refinance",
       "Property condition and appraisal results after rehab",
       "Leverage limits for the refinance type used",
       "Credit and reserves, as everywhere"],
 obj=[("Will I get all my capital back out?","Sometimes, not reliably. Proceeds are appraisal times program leverage minus payoff and costs, gated by timing rules. Model the conservative case; treat full recovery as upside, not a plan."),
      ("Seasoning kills my velocity.","Timing rules are real constraints and differ by program. Knowing the applicable clock before buying lets you sequence capital deliberately instead of discovering the wait mid-project.")],
 faqs=[("How long before the new appraised value counts?","Programs differ: some use current value after defined ownership periods, others apply cost-based limits early. The applicable rule is a program fact your review should establish before you buy, not after."),
       ("Does documented rehab change the valuation?","It supports the appraisal narrative and matters under some programs' rules. Keep invoices and scope records regardless; undocumented rehab helps no one."),
       ("Can I refinance before the property is leased?","Some programs consider rent-ready properties on market rent; a signed lease is stronger and more widely accepted. The difference changes your rent-up planning."),
       ("What ratio does the refinance need?","Program thresholds vary and interact with leverage: a stronger ratio can support more proceeds. This is sized in review, not assumed."),
       ("Should the BRRRR refinance be cash-out or rate-and-term?","It depends on payoff structure and timing rules; classifications carry different rules on proceeds and seasoning. The review classifies the scenario correctly before promising anything.")],
 related=["bridge-loan-refinance","cash-purchase-refinance","cash-out-refinance"]),

dict(id="DSCR-LP007", slug="working-professionals", label="Working professionals",
 angles=["DSCR-A004"], index=False,
 query="rental property loan while working full time (hypothesis; overlaps LP001/LP004 intents)",
 title="Rental Financing Around a Full-Time Job | Stonehaven",
 desc="A practical workflow for organizing a rental-financing decision alongside a full-time job: what to prepare, what to compare, and what to decide once.",
 h1="Another rental starts with a clear deal review",
 sub="The constraint is not qualification; it is attention. This page organizes the financing decision so it takes hours of your calendar, not weeks of it.",
 answer="Salaried professionals finance rentals through the same paths as anyone: conventional investment loans using documented income, or DSCR programs sized on the property's rent against its qualifying payment (PITIA). The relevant limitation: neither path offers a busy person fewer requirements or faster funding; what improves is how the decision is organized. This page is a workflow, not a product promise.",
 scen_h="An illustrative week, organized",
 scen=["An employed buyer finds a promising listing on a Tuesday. Instead of five evenings of scattered research, the decision splits into three fixed blocks: one evening assembling the property's numbers, one review conversation comparing structures, one decision block with the comparison in hand. Illustrative workflow, not a promise about anyone's schedule.",
      "The point of structure is a decision made once, on complete numbers, instead of repeatedly on partial ones."],
 fit_h="Which path fits an employed file",
 fit=["Strong W-2 income often prices well conventionally, and that path deserves first look. A DSCR structure can fit when property-count limits, DTI interactions with other properties, or documentation friction make the property-based path cleaner.",
      "The comparison is the same as everyone's: total cost, reserves, program rules. Employment changes convenience, not eligibility."],
 module=dict(type="checklist", h="The one-evening preparation list",
  intro="Everything a useful review needs, collectable in one sitting:",
  items=[("The property's numbers","Price, expected rent (and its source), tax figure, insurance quote or estimate, any association dues."),
         ("Your cash position","What you can put down and what remains after closing; reserves count."),
         ("Your credit picture","A recent score range and any events worth flagging early."),
         ("Your portfolio facts","Properties owned, financed count, and how title is held or will be held."),
         ("Your timing","Offer deadline, close-by date, or exploratory. Timing shapes which questions matter first.")]),
 qual=["Credit, leverage and reserves as in any file",
       "Financed-property counts under conventional rules where relevant",
       "Eligible rent treatment for the property",
       "Entity questions if vesting beyond personal name"],
 obj=[("I do not have time for a drawn-out process.","No one does. The honest version: preparation shortens the review, but underwriting timelines belong to lenders and are not promised here. What you control is arriving with complete numbers."),
      ("Should I just use conventional financing?","Maybe. If your file prices well conventionally, the review should say exactly that. The comparison exists to route you correctly, not to sell one structure.")],
 faqs=[("Does a full-time job help or hurt DSCR qualification?","Neither. DSCR programs center on the property's numbers; your employment mainly matters through credit, assets and reserves. Conventional paths use your income directly and may fit well."),
       ("Can I do the whole review remotely?","Yes; the preliminary review runs by phone and email, and documents move electronically when you proceed with a lender."),
       ("What is the single most valuable thing to prepare?","A real insurance quote and the post-sale tax figure. They move the payment more than most buyers expect and are the difference between an estimate and an answer."),
       ("Will more properties complicate my W-2 file later?","Financed-property counts and DTI interactions can shape conventional options as portfolios grow, which is when property-based structures often earn their place. Worth mapping one property ahead."),
       ("Is this page suggesting employed buyers get special terms?","No. Terms follow the file and the program, not the job. This page organizes the decision; it does not change eligibility.")],
 related=["experienced-landlords","self-employed-investors","out-of-state-investors"]),

dict(id="DSCR-LP008", slug="out-of-state-investors", label="Out-of-state investors",
 angles=["DSCR-A005","DSCR-A017"], index=True,
 query="buying rental property out of state financing dscr",
 title="Financing an Out-of-State Rental | Stonehaven",
 desc="What local facts matter when financing a rental remotely: property-state availability, rent support, operating costs, and lender DSCR versus owner cash flow.",
 h1="A different market. The same need for clear numbers",
 sub="Remote investing multiplies the places assumptions hide: rent you have not verified, taxes you have not lived with, management you cannot do yourself. The financing review is where those assumptions meet paper.",
 answer="Financing follows the property's state: program availability, taxes, insurance realities and local rent evidence all attach to where the rental sits, not where you live. A DSCR review sizes eligible rent against the qualifying payment (PITIA) using the property's local numbers. The relevant limitation, worth reading twice: the lender's qualifying ratio is not your cash flow. Management, vacancy, maintenance and capital expenses come out of the same rent after the ratio is computed.",
 scen_h="An illustrative remote purchase",
 scen=["An investor in one state buys a $220,000 rental in another, projecting $1,900 rent. The listing's tax figure is the seller's homesteaded bill; the real post-sale bill is higher. Insurance in the destination market runs above the buyer's home-state intuition. Management takes its share. The deal may still work; it works differently than the spreadsheet from three states away said. Illustrative example, not a customer.",
      "The review's job is replacing imported assumptions with the property state's actual numbers before the offer, not after."],
 fit_h="Two views of the same property",
 fit=["The lender's view: eligible rent against PITIA, computed to program rules, deciding qualification and leverage. The owner's view: the same rent minus management, vacancy allowance, maintenance and reserves, deciding whether the investment feeds you or you feed it.",
      "Both views matter and neither substitutes for the other. A property can pass the lender's ratio and still run negative for its owner; the review shows both columns."],
 module=dict(type="table", h="Lender DSCR versus owner cash flow",
  intro="The same rental, two honest columns. Illustrative categories; the review fills real figures:",
  cols=("Line","Lender qualification view","Owner cash-flow view"),
  items=[("Rent","Eligible rent per lease or appraiser market rent","Actual collected rent"),
         ("Payment (PITIA)","Counted","Counted"),
         ("Property management","Not in the standard residential ratio","Counted, commonly a meaningful share of rent"),
         ("Vacancy","Not in the ratio","Counted as an allowance"),
         ("Maintenance and capital items","Not in the ratio","Counted, or they count themselves later"),
         ("Bottom line","Qualifying ratio","What actually lands in your account")]),
 qual=["Program availability in the property's state",
       "Local rent evidence and the appraiser's market analysis",
       "Post-sale property taxes and real insurance quotes",
       "Property type, condition and location rules",
       "Credit and reserves, as everywhere"],
 obj=[("Can I even finance a property in a state I do not live in?","Financing follows the property's state and the programs available there; your residence state is mostly an administrative fact. Availability is confirmed per scenario rather than promised in general."),
      ("The ratio passes; why does the review keep asking about management?","Because the ratio is a qualification tool, not an investment verdict. Management, vacancy and maintenance decide your actual return, and a review that ignores them flatters the deal.")],
 faqs=[("Does it matter that I will not self-manage?","For the standard residential qualification ratio, management expense is typically not included. For your investment, it is one of the largest real costs. Both facts belong in the decision."),
       ("Whose rent number gets used?","The appraiser's local market analysis or the lease, per program rules. Your home-market intuition about rents does not transfer and does not get used."),
       ("How do I verify taxes and insurance remotely?","Use the destination county's post-sale treatment, not the listing figure, and a real local insurance quote. These two lines correct most long-distance spreadsheets."),
       ("Are all states available?","Program availability varies by state and lender; no universal claim is made here. The review confirms availability for the specific property's state."),
       ("What belongs in my remote operating budget?","Management, vacancy allowance, maintenance, capital reserves, travel if you inspect, and local compliance costs. If the deal only works with those at zero, it does not work.")],
 related=["experienced-landlords","long-term-rentals","short-term-rentals"]),

dict(id="DSCR-LP009", slug="portfolio-growth", label="Portfolio growth",
 angles=["DSCR-A006","DSCR-A030"], index=True,
 query="dscr vs portfolio loan multiple rental properties",
 title="Portfolio Growth: DSCR vs Portfolio Loans | Stonehaven",
 desc="When to compare another single-property loan with portfolio or commercial financing: exposure limits, ownership, operational complexity and product routing.",
 h1="More properties call for another financing comparison",
 sub="The structure that financed door three may not be the right architecture for door eight. This page is about when the product question changes.",
 answer="Growing portfolios finance property by property until constraints appear: conventional financed-property limits, lender exposure caps to one borrower, operational complexity across many notes, or a property that outgrows residential classification. At that point the comparison widens: another single-property DSCR loan, a portfolio facility, or commercial financing. The relevant limitation: each path carries different recourse, reporting and exposure rules, and no page can promise which fits; the routing is the review.",
 scen_h="An illustrative routing decision",
 scen=["An investor with six financed rentals is buying two more and weighing a small apartment building. Conventional property-count rules constrain part of the plan; a lender's exposure cap constrains another part; the apartment building is not a residential DSCR question at all. One growth plan, three different financing architectures. Illustrative example, not a customer.",
      "The expensive mistake is answering an architecture question with another one-off loan because it is familiar."],
 fit_h="Single-property loans against portfolio structures",
 fit=["Single-property DSCR loans keep each deal independent: separate notes, separate qualification on each property's rent, flexibility to sell one without touching others. Portfolio and commercial structures consolidate: one facility, blanket or cross-collateral terms, different reporting, often different recourse.",
      "Consolidation can simplify growth and can also concentrate risk. Which serves the plan depends on exposure limits, hold intentions, and how much operational complexity you want to carry."],
 module=dict(type="checklist", h="Signals the architecture question has arrived",
  intro="Any two of these usually means the comparison is worth running formally:",
  items=[("Financed-property counts bind","Conventional rules cap financed properties under defined counting; your next purchase tests the cap."),
         ("A lender's exposure limit appears","Aggregate exposure to one borrower is capped by many lenders; growth pushes against it."),
         ("Five or more units enters the plan","Larger residential and mixed-use assets route to commercial analysis, where income is assessed as NOI against annual debt service, a different calculation entirely."),
         ("Note management becomes a job","Many separate loans mean many payments, escrows, insurance renewals and maturities to track."),
         ("Entity structure is consolidating","Holding structures with partners or layered LLCs raise guarantor and reporting questions better solved once, at the facility level.")]),
 qual=["Aggregate exposure and property-count rules across lenders and programs",
       "Each property's rent and condition for single-property paths",
       "Entity, guarantor and reporting requirements for facilities",
       "Recourse terms, which differ across structures",
       "Prepayment and release provisions when properties may be sold individually"],
 obj=[("Is a portfolio loan cheaper per property?","Not reliably. Facilities trade convenience and capacity against different pricing, covenants and recourse. The comparison is total structure cost against the growth plan, not a per-door rate contest."),
      ("Can I keep buying one loan at a time forever?","Until a cap binds: property counts, lender exposure, or your own operational bandwidth. Mapping the caps one purchase early keeps growth from stalling mid-contract.")],
 faqs=[("How many DSCR loans can one investor have?","There is no universal number. Program rules and lender exposure caps vary; conventional lending separately applies defined property-count rules. Your actual headroom is a review question."),
       ("What changes at five or more units?","The property typically routes to commercial analysis: income assessed as net operating income against annual debt service, different documentation and different programs. Stonehaven routes those scenarios to its commercial review rather than forcing a residential frame."),
       ("Do portfolio facilities require my whole portfolio as collateral?","Structures vary: blanket liens, cross-collateralization and release provisions are negotiated terms. Understanding release mechanics matters if you may sell properties individually."),
       ("Will consolidating change my recourse exposure?","It can. Guaranty structures across facilities differ from single-property notes. No structure here is represented as nonrecourse; guaranty terms are scenario facts to establish."),
       ("Should my LLCs consolidate before the financing does?","Ownership architecture and financing architecture interact; changing either mid-process complicates both. Bring the entity map to the review before restructuring.")],
 related=["experienced-landlords","llc-investors","2-4-unit-properties"]),
]
