# -*- coding: utf-8 -*-
"""Content configuration for the /heloc/<slug> persona landing pages.
Edit copy HERE, then rebuild: python3 scripts/build-heloc-personas.py
Every page carries two intent variants (renovation / consolidation).
House rules baked into the linter: no em dashes, no rates, no guarantees,
no 'no credit check', no VA/government implication, no persona-exclusive
terms, no assumed circumstances. scripts/ is stripped from deploys."""

# Shared, verified process description (matches the live HELOC funnels).
PROCESS = [
    ("Send the basics", "State, property, rough numbers and what the money is for. No SSN and no hard credit pull to compare initial options."),
    ("Talk it through", "A licensed specialist calls you back, usually within one business day, and walks through HELOC and fixed home equity structures side by side."),
    ("Compare and decide", "You see the trade-offs in plain numbers. Any loan is subject to lender underwriting, documentation and program availability."),
]

REVIEW_NOTE = "The answer depends on the lender and your file. A specialist confirms this during review."

# Base FAQs appended to every page (verified product facts / process).
BASE_FAQS = {
    "renovation": [
        {"q": "Does a HELOC replace my current mortgage?",
         "a": "No. A HELOC is a separate second lien. Your existing first mortgage and its terms stay exactly as they are. The HELOC is its own loan with its own payment, costs and repayment obligations."},
        {"q": "Which states does Stonehaven serve for home loans?",
         "a": "Georgia, Alabama, Tennessee, Florida, North Carolina and South Carolina. Company NMLS #1752355."},
        {"q": "What happens after I send my details?",
         "a": "A licensed specialist replies personally, usually within one business day, and compares HELOC and fixed home equity options for your numbers. Nothing here is an approval; any loan is subject to lender underwriting."},
    ],
    "consolidation": [
        {"q": "Is consolidating credit cards with a HELOC the same as paying them off?",
         "a": "No. The balances are restructured into a loan secured by your home, not erased. That can change the monthly picture, but the repayment period, fees and total cost over time matter as much as the payment, and your home secures the new borrowing."},
        {"q": "Will checking my options affect my credit?",
         "a": "There is no hard credit pull to compare initial options. A hard inquiry may occur later if you continue with a lender."},
        {"q": "Which states does Stonehaven serve for home loans?",
         "a": "Georgia, Alabama, Tennessee, Florida, North Carolina and South Carolina. Company NMLS #1752355."},
    ],
}

# visual keys map to SVG scene builders in build-heloc-personas.py
PERSONAS = [
dict(slug="homeowners", label="Homeowners", visual="home_plans",
 ren=dict(
  title="HELOC for Home Renovations | Stonehaven Lending",
  h1="New kitchen. Same address.",
  sub="A home equity line of credit is a separate loan against your equity. Your existing first mortgage stays in place while you explore financing for the renovation.",
  sit_h="You like the house. The kitchen disagrees.",
  sit_p1="Most renovation conversations start the same way: the home still fits, one part of it does not. The question is how to pay for the work without unwinding financing that already works.",
  sit_p2="That is the comparison this page is for. Not a sales pitch for one product, a clear look at how a separate line of credit sits next to the mortgage you already have.",
  dist_h="How the first mortgage and a HELOC fit together",
  dist_p1="Your first mortgage is one loan with its own balance, payment and terms. A HELOC is a second, separate loan secured by the same home. Opening one does not change the first mortgage, and closing one does not either.",
  dist_p2="It does add a second payment. The honest math is total cost across both loans, which is exactly what a specialist walks through before anyone applies.",
  bens=["Your existing first mortgage and its terms stay as they are",
        "Draw on the line in stages as renovation costs actually arrive",
        "Compare HELOC and fixed home equity structures before choosing"],
  faqs=[{"q": "How much of the renovation can a HELOC cover?", "a": "It depends on your equity, the lender's combined loan-to-value limits and your file. A specialist sizes it from your estimated value and mortgage balance before anything formal.", "review": True}],
  intake="Tell us about the home and the project. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven Lending",
  h1="Compare a new plan for credit card balances.",
  sub="A home equity line of credit is a separate loan against your equity, secured by your home. Your first mortgage stays in place while you compare whether restructuring card balances makes sense.",
  sit_h="The balances are manageable. The interest is not.",
  sit_p1="Card balances have a way of costing more than what was bought with them. Consolidating through home equity is one way to restructure that cost, and it deserves a clear-eyed comparison, not a slogan.",
  sit_p2="The comparison that matters: what the cards cost now versus what a home-secured line would cost over its full repayment period, fees included.",
  dist_h="How the first mortgage and a HELOC fit together",
  dist_p1="Your first mortgage stays exactly as it is. The HELOC is a second, separate loan against the same home, with its own payment and terms.",
  dist_p2="Moving card debt onto it means the debt becomes secured by your home. That is a real trade, and it is the first thing a specialist puts on the table.",
  bens=["Your existing first mortgage and its terms stay as they are",
        "One structure to compare against several card balances",
        "The full picture: repayment period, fees and total cost, not just the payment"],
  faqs=[{"q": "Will consolidating actually save me money?", "a": "Sometimes, not always. It depends on what your cards cost, the terms a lender offers, the fees and how long you take to repay. We compare total cost over time, and if the numbers do not work we say so."}],
  intake="Share the rough numbers. A specialist compares the cost of the cards against a home-secured plan.",
  purpose="Debt consolidation")),

dict(slug="veteran-homeowners", label="Veteran homeowners", visual="home_flagless",
 ren=dict(
  title="HELOC for Veteran Homeowners: Renovations | Stonehaven",
  h1="Make the next chapter feel like home.",
  sub="A HELOC is a separate line of credit against your equity. Whatever loan you bought or refinanced with, including a VA loan, your existing first mortgage stays in place while you explore it.",
  sit_h="The house served one chapter. The next one has different plans.",
  sit_p1="Plenty of veteran homeowners hold a first mortgage worth keeping. When a renovation comes up, the instinct to protect that loan is a good one.",
  sit_p2="A separate line of credit is one way to fund the work without touching it. Whether it is the right way depends on your numbers, which is what the comparison is for.",
  dist_h="Questions worth asking before changing an existing mortgage",
  dist_p1="What are the terms of the loan you have today? What would replacing it cost over the full term? What does a second, separate loan cost instead? Those three questions settle most renovation financing decisions.",
  dist_p2="A specialist walks through all three with your actual numbers. To be clear: a HELOC is not a VA product, and Stonehaven is not affiliated with any government agency. This page is for any homeowner, and the terms offered do not depend on service history.",
  bens=["Your existing first mortgage, VA or otherwise, stays as it is",
        "Fund the project in stages as work is completed",
        "A named specialist, not a call center, walks through the trade-offs"],
  faqs=[{"q": "I have a VA loan. Does a HELOC affect it?", "a": "No. A HELOC is a separate, non-VA second lien. Your VA first mortgage and its terms stay as they are. The HELOC itself is a conventional product with its own costs and is not backed by the VA or any government agency."}],
  intake="Tell us about the home and the project. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="A clear comparison for the next chapter.",
  sub="A HELOC is a separate loan secured by your home. Your existing first mortgage, VA or otherwise, stays in place while you compare restructuring card balances.",
  sit_h="Good mortgage. Expensive cards.",
  sit_p1="Holding a first mortgage worth keeping while carrying card balances is a common position, and there is a disciplined way to look at it.",
  sit_p2="Compare what the cards cost against what a home-secured line would cost over its full repayment period. If restructuring wins, it wins on numbers.",
  dist_h="Questions worth asking before changing anything",
  dist_p1="Would consolidating actually lower the total cost, fees included? How long would repayment run? And what does securing the debt with your home mean if circumstances change?",
  dist_p2="A specialist answers all three with your figures. A HELOC is not a VA product and carries no government backing; terms do not depend on service history.",
  bens=["Your existing first mortgage stays exactly as it is",
        "The comparison covers total cost, not just the monthly payment",
        "Straight answers from a licensed specialist within one business day"],
  faqs=[{"q": "Does my service history change the terms?", "a": "No. A HELOC is a conventional product; the terms offered depend on your equity, credit profile and the lender's program, not on service history. We say this plainly because pages that imply otherwise are misleading."}],
  intake="Share the rough numbers. A specialist compares the cost of the cards against a home-secured plan.",
  purpose="Debt consolidation")),

dict(slug="career-moms", label="Busy working households", visual="calendar_kitchen",
 ren=dict(
  title="HELOC for Busy Households: Renovations | Stonehaven",
  h1="A kitchen that keeps up with the calendar.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place, and the exploring part is built to fit into a full week.",
  sit_h="The renovation is planned. The spare hours are not.",
  sit_p1="In a household where the calendar runs the show, financing research is the task that keeps sliding. The project is scoped, the quotes are close, and the money question is still open.",
  sit_p2="This page is the short version: what a separate line of credit is, what it costs to explore and what the actual next step looks like.",
  dist_h="One clear next step",
  dist_p1="Send the basics below, five minutes, no documents. A licensed specialist calls back, usually within one business day, and does the comparison work for you: HELOC versus fixed home equity versus leaving things alone.",
  dist_p2="The same process everyone gets, laid out so it needs exactly one decision from you today: whether to start.",
  bens=["Five minutes to start, no documents at this stage",
        "Your existing first mortgage stays as it is",
        "One callback covers the whole comparison"],
  faqs=[{"q": "How much time does the whole process take?", "a": "Starting takes about five minutes. The callback is one conversation. Beyond that, timelines depend on the lender, appraisal needs and your documents; a specialist gives you a real schedule up front rather than a promise.", "review": True}],
  intake="Five minutes now, one callback later. Tell us about the home and the project.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="A full calendar. A clearer financing plan.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare whether restructuring card balances is worth it.",
  sit_h="No time for a research project. Enough time for a comparison.",
  sit_p1="Comparing card costs against a home-secured line is genuinely a one-conversation exercise when someone else does the math.",
  sit_p2="Send the balances and rough numbers; a specialist lays out what the cards cost now, what a HELOC structure would cost over its repayment period, and where the break-even sits.",
  dist_h="One clear next step",
  dist_p1="The form below takes about five minutes. The callback covers everything: costs, fees, repayment period and the fact that the new borrowing is secured by your home.",
  dist_p2="If the numbers do not favor consolidating, the specialist says so and you have lost five minutes, not an afternoon.",
  bens=["One conversation instead of a research project",
        "Total-cost comparison, fees and repayment period included",
        "Your existing first mortgage stays as it is"],
  faqs=[{"q": "Can I do this whole thing by phone and email?", "a": "Yes. The comparison happens on one call, and documents move by email when you decide to go further. In-person is never required."}],
  intake="Share the rough numbers. One callback covers the whole comparison.",
  purpose="Debt consolidation")),

dict(slug="empty-nesters", label="Households rethinking space", visual="room_convert",
 ren=dict(
  title="HELOC for Repurposing Rooms | Stonehaven Lending",
  h1="Make room for the next chapter.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you explore turning underused space into space you will actually use.",
  sit_h="A room that used to work harder.",
  sit_p1="Homes accumulate rooms that no longer earn their keep: the spare room that became storage, the formal dining room nobody dines in. Repurposing them is usually cheaper than moving and more satisfying than ignoring them.",
  sit_p2="A study, a guest room, a hobby space, a gym. The work is real construction with a real budget, and that budget is what a separate line of credit is built to fund.",
  dist_h="Improving the home for how it is used now",
  dist_p1="The best conversions start with use, not square footage: who is in the room, how often, doing what. Scope follows, then an estimate, then the financing amount.",
  dist_p2="A specialist helps size the borrowing to the scope you actually settle on, drawn in stages as the work happens rather than all at once.",
  bens=["Fund a conversion without touching the first mortgage",
        "Draw in stages as the project progresses",
        "Size the line to the scope, not a round number"],
  faqs=[{"q": "Is a HELOC better than a renovation loan for this?", "a": "It depends on scope and how you want to draw funds. Lines suit staged projects; fixed home equity loans suit one known amount. A specialist compares both against your project.", "review": True}],
  intake="Tell us about the room and the plan. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="Review the borrowing plan for what comes next.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances for the years ahead.",
  sit_h="A good moment to tidy the balance sheet.",
  sit_p1="Changes in household routine are natural moments to look at what the debts cost. Card balances that accumulated over busy years may be worth restructuring on calmer terms.",
  sit_p2="The comparison is straightforward: current card costs against a home-secured line over its full repayment period, with fees counted.",
  dist_h="Repayment timing matters as much as the payment",
  dist_p1="A lower monthly payment stretched over many more years can cost more in total. The comparison a specialist runs shows both numbers side by side, so the decision is made on the whole picture.",
  dist_p2="And because the new borrowing is secured by your home, the specialist treats that trade seriously rather than burying it in fine print.",
  bens=["Total-cost comparison across payment and repayment period",
        "Your existing first mortgage stays as it is",
        "A licensed specialist, one business day, no obligation"],
  faqs=[{"q": "Does the repayment period match up with our plans?", "a": "That is exactly the right question. HELOC draw and repayment periods vary by lender and program; a specialist maps them against the timeline you have in mind before anything is applied for.", "review": True}],
  intake="Share the rough numbers and your timing. A specialist runs the comparison.",
  purpose="Debt consolidation")),

dict(slug="staying-put", label="Long-term homeowners", visual="exterior_interior",
 ren=dict(
  title="Renovate and Stay: HELOC Options | Stonehaven Lending",
  h1="Love the neighborhood. Ready for a new kitchen.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund the update that makes staying the easy choice.",
  sit_h="The location is right. The finishes are from another decade.",
  sit_p1="When the neighborhood, the schools and the commute all work, the housing question is rarely whether to stay. It is how to make the house current without giving up financing that took years to build.",
  sit_p2="A separate line of credit funds the update while the mortgage underneath stays untouched.",
  dist_h="Improve the house, or make a larger housing change?",
  dist_p1="It is worth pricing both honestly. A move carries transaction costs, a new financing environment and the loss of terms you already hold. A renovation carries a construction budget and a second loan payment.",
  dist_p2="Neither is automatically cheaper. A specialist can put your actual numbers on both sides so the decision is made with the whole picture in view.",
  bens=["Keep the first mortgage you spent years paying into",
        "Fund the update in stages as the work happens",
        "An honest renovate-versus-move numbers comparison"],
  faqs=[{"q": "How do I compare renovating against moving?", "a": "Price both: the full project budget plus the HELOC's costs on one side; selling costs, purchase costs and financing a new home at today's terms on the other. A specialist helps build that side-by-side with your figures."}],
  intake="Tell us about the home and the update. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="Explore a different debt plan while keeping the first mortgage in place.",
  sub="A HELOC is a separate loan secured by your home. The mortgage you have spent years paying down stays exactly as it is.",
  sit_h="Years of equity. A stack of card statements.",
  sit_p1="Long-term homeowners often sit on meaningful equity while carrying card balances that cost far more than any mortgage ever did. That gap is worth examining.",
  sit_p2="Restructuring cards through a home-secured line can change the cost picture, and it can also stretch repayment and put your home behind the debt. Both halves belong in the comparison.",
  dist_h="What staying put makes possible",
  dist_p1="Because you are not planning to sell, the repayment period on a second lien can be planned calmly against how long you will hold the home.",
  dist_p2="A specialist runs the numbers over the full period: payment, fees, total cost and the security trade, side by side with what the cards cost today.",
  bens=["The first mortgage stays as it is",
        "Repayment planned against how long you will hold the home",
        "Total cost compared honestly against the cards"],
  faqs=[{"q": "Is using equity for card debt a good idea?", "a": "It can be, and it can be a mistake. The debt becomes secured by your home and the repayment period may be longer. It is a good idea only when the total cost, not just the payment, is clearly better and the repayment plan is realistic. That is the comparison we run."}],
  intake="Share the rough numbers. A specialist compares the cost of the cards against a home-secured plan.",
  purpose="Debt consolidation")),

dict(slug="next-chapter", label="Planning toward retirement", visual="comfortable_home",
 ren=dict(
  title="Plan the Home for the Years Ahead | Stonehaven",
  h1="Plan the home for the years ahead.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund practical improvements on your own timeline.",
  sit_h="The home is staying. Make it work for the long run.",
  sit_p1="Improvements made a few years ahead of a life change are usually calmer and better priced than ones made under pressure: a first-floor bath, better lighting, a low-maintenance exterior, a kitchen that will not need touching again for twenty years.",
  sit_p2="Funding them with a separate line keeps the existing mortgage intact and lets the work happen in planned stages.",
  dist_h="Repayment timing and the household plan",
  dist_p1="The honest question for any borrowing at this stage is how repayment maps against expected income over the repayment period, not just this year.",
  dist_p2="A specialist puts the draw period, the repayment period and the payment math against your timeline. Borrowing does not improve anyone's retirement security by itself; a well-planned project with clearly affordable repayment can still be the right call.",
  bens=["Improvements on your schedule, funded in stages",
        "The existing first mortgage stays as it is",
        "Repayment mapped honestly against your timeline"],
  faqs=[{"q": "How long do HELOC draw and repayment periods run?", "a": "It varies by lender and program; many lines have a multi-year draw period followed by a longer repayment period. A specialist confirms the exact structure being offered before you commit.", "review": True}],
  intake="Tell us about the home and the plan. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="Compare repayment plans for the next chapter.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances with the years ahead in view.",
  sit_h="Simplify before the next chapter, with eyes open.",
  sit_p1="Heading toward a change in working life with card balances in tow is common, and consolidating them can simplify the monthly picture.",
  sit_p2="It can also stretch repayment further into years when income may look different. That trade deserves a plain-numbers look before anything is signed.",
  dist_h="Affordability across the whole repayment period",
  dist_p1="The comparison a specialist runs covers the payment today, the payment after any draw period ends, and the total cost across the full term, next to what the cards cost now.",
  dist_p2="Eligibility is decided by lenders on the whole file; no income source settles it in advance, and we will not pretend otherwise.",
  bens=["Payment now and payment later, both on the table",
        "Total cost compared against the cards, fees included",
        "The first mortgage stays as it is"],
  faqs=[{"q": "What happens to the payment after the draw period?", "a": "On many lines the payment steps up when repayment begins. The specialist shows you both numbers before you decide, because that later payment is the one that has to fit the plan.", "review": True}],
  intake="Share the rough numbers and your timeline. A specialist runs the comparison.",
  purpose="Debt consolidation")),

dict(slug="multigenerational-living", label="Multigenerational households", visual="floorplan",
 ren=dict(
  title="HELOC for Multigenerational Space | Stonehaven",
  h1="More room for life under one roof.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund the space a fuller household needs.",
  sit_h="One address, several routines.",
  sit_p1="Households combine for a hundred good reasons, and the house rarely arrives ready. The projects are familiar: another bathroom, a guest room that works year-round, a separate entrance, a kitchen that can serve more people.",
  sit_p2="These are real construction projects with staged costs, which is the shape of spending a line of credit handles well.",
  dist_h="The spaces that make shared living work",
  dist_p1="Extra bathrooms carry the biggest daily impact. Adaptable rooms, private entries and sound separation carry the long-term value of privacy.",
  dist_p2="Scope and permits are the builder's department; check local permitting before committing to plans. We handle the financing comparison. We do not promise any project increases the property's value or produces rental income, and any accessory-unit rules are a local matter to verify first.",
  bens=["Fund staged construction as the work happens",
        "The existing first mortgage stays as it is",
        "Size the borrowing to the scope you settle on"],
  faqs=[{"q": "Can a HELOC fund an addition or accessory space?", "a": "Lines are commonly used for additions and conversions. Whether your specific project fits depends on equity, the lender's limits and local permitting, which the lender does not decide for you.", "review": True}],
  intake="Tell us about the household plan and the project. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="One household. A clearer financing comparison.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances.",
  sit_h="More people under one roof, more moving costs.",
  sit_p1="Combining households often leaves card balances behind: moving costs, furniture, the first round of house adjustments. Once the dust settles, those balances deserve a proper look.",
  sit_p2="A home-secured line is one way to restructure them. Whether it is the right way is a total-cost question, and the borrowing sits on the homeowner's file, not the household's.",
  dist_h="Whose loan is it?",
  dist_p1="A HELOC belongs to the homeowner borrowing it, secured by the home. Household members' balances can be paid with the proceeds, but the repayment obligation is the borrower's.",
  dist_p2="A specialist lays that out clearly along with cost, fees and repayment period, so the household decision is made with the structure understood.",
  bens=["One structure compared against several balances",
        "Clear on whose obligation the new borrowing is",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Can proceeds pay off cards that are not in my name?", "a": "Proceeds are generally yours to direct once the loan funds, but the borrowing and its repayment are yours. Lender rules on payoff-at-closing vary; a specialist confirms the mechanics.", "review": True}],
  intake="Share the rough numbers. A specialist compares the cost of the cards against a home-secured plan.",
  purpose="Debt consolidation")),

dict(slug="busy-family-households", label="Households balancing many responsibilities", visual="household_calendar",
 ren=dict(
  title="HELOC for Busy Households: Renovations | Stonehaven",
  h1="A home that works around more of life.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund the changes that make the house serve everyone in it.",
  sit_h="The house is busy. The project list is real.",
  sit_p1="When a home carries a lot of life, the improvement list writes itself: a bathroom that relieves the morning queue, a flexible room that changes jobs by the season, storage that ends the hallway pile-up.",
  sit_p2="The discipline is choosing which project, for how much, and when. Financing should follow that decision, not drive it.",
  dist_h="Project, amount, timing, in that order",
  dist_p1="Pick the project with the biggest daily payoff. Price it with real quotes. Then size the borrowing to that number and schedule draws to the work.",
  dist_p2="A specialist helps with the last step and sanity-checks the middle one. Borrowing more than the project needs is the most common and most avoidable mistake.",
  bens=["Borrow to the project, not a round number",
        "Draws follow the work schedule",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Can we start with one project and fund another later?", "a": "That staging pattern is what lines of credit are for: draw for the first project, repay, draw again within the draw period and your available line. Structure specifics vary by lender.", "review": True}],
  intake="Tell us which project comes first. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="A clear next step among competing priorities.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances.",
  sit_h="Ten open tabs. One financial question worth closing.",
  sit_p1="In a full household, the card balances are usually item six on a list that never gets past item three. Closing that item takes one comparison, not a project.",
  sit_p2="Send the rough numbers; a specialist does the math on what the cards cost against a home-secured structure and calls back with both totals.",
  dist_h="One decision today",
  dist_p1="The only decision this page asks for is whether to run the comparison. The callback covers cost, fees, repayment period and the home-security trade in one conversation.",
  dist_p2="If it does not pencil, you will hear that plainly and the item comes off the list either way.",
  bens=["One comparison closes the open question",
        "Total cost, fees and repayment period in one view",
        "The first mortgage stays as it is"],
  faqs=[{"q": "What if our situation is complicated?", "a": "Complicated files are normal: multiple balances, variable income, shared obligations. The specialist reviews the actual picture rather than a formula, and tells you what lenders will want to see.", "review": True}],
  intake="Share the rough numbers. One callback covers the whole comparison.",
  purpose="Debt consolidation")),

dict(slug="home-office", label="Professionals working from home", visual="office",
 ren=dict(
  title="HELOC for a Home Office Build | Stonehaven Lending",
  h1="Give the workday its own room.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund a proper workspace.",
  sit_h="The dining table did its best.",
  sit_p1="Years into working from home, the temporary setup is still temporary: the table that hosts both dinner and deadlines, the video calls staged against the least cluttered wall.",
  sit_p2="A dedicated office is a bounded, priceable project: a room conversion, built-ins, wiring, sound, light. Exactly the kind of scope a line of credit can fund in stages.",
  dist_h="Scoping a workspace that will last",
  dist_p1="The projects that hold up start with the work itself: how many screens, how much call time, what storage, what separation from the rest of the house.",
  dist_p2="Scope that honestly, price it with quotes, and size the borrowing to it. We make no claims about productivity or tax treatment; consult a tax professional on deductibility. This is a construction budget and a financing comparison, done properly.",
  bens=["A bounded project with a clear budget",
        "Draw in stages as the build progresses",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Does a home office project qualify for a HELOC?", "a": "The financing does not care what the room is for; it cares about your equity, the lender's limits and your file. The office is your call. The sizing is what a specialist confirms.", "review": True}],
  intake="Tell us about the space and the plan. A specialist compares your options personally.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="Bring a clear plan to the financing decision.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances.",
  sit_h="You compare vendors for a living. Compare this the same way.",
  sit_p1="Professionals who evaluate proposals all day tend to want the same rigor applied to their own balance sheet: line items, totals, terms, exit costs.",
  sit_p2="That is the format the comparison comes in. What the cards cost now, what a home-secured line costs over its full repayment period, fees itemized, security trade stated.",
  dist_h="The comparison, in a format worth reading",
  dist_p1="A specialist prepares the numbers side by side and walks through them on one call: payment, repayment period, total cost, and what changes because the debt becomes secured by your home.",
  dist_p2="No urgency mechanics, no rounded promises. If keeping the cards costs less, the comparison will show it.",
  bens=["An itemized comparison, not a pitch",
        "Total cost over the full repayment period",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Can I see the numbers before deciding anything?", "a": "Yes. The comparison comes before any application, and there is no hard credit pull to see it. If you go forward, a lender's formal terms follow underwriting."}],
  intake="Share the rough numbers. A specialist prepares the comparison.",
  purpose="Debt consolidation")),

dict(slug="shift-workers", label="Professionals with demanding schedules", visual="shift_calendar",
 ren=dict(
  title="HELOC for Shift-Work Households: Renovations | Stonehaven",
  h1="Plan a home that works around the schedule.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place, and the process fits around a schedule that is not nine to five.",
  sit_h="The schedule is demanding. The house should not be.",
  sit_p1="Households running on shifts know exactly which improvements matter: a bedroom that stays dark and quiet at noon, a bathroom that removes the bottleneck, a kitchen that works at odd hours.",
  sit_p2="The projects are practical and priceable. The financing conversation should be equally practical.",
  dist_h="How the next step actually works",
  dist_p1="Send the form below whenever suits, at any hour. A licensed specialist calls back during business hours, usually within one business day; reply with a better time and the callback moves to it within those hours.",
  dist_p2="You can also call (470) 970-4979 directly or book a slot through the site's scheduling page. Those are the real contact options, stated plainly.",
  bens=["Start online at any hour, no documents needed",
        "Callback timed to suit, within business hours",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Do you offer evening or overnight appointments?", "a": "Calls happen during business hours, Eastern time. What we can do is schedule precisely: name the window that works and the specialist calls then. We would rather say this plainly than pretend to a 24-hour desk."}],
  intake="Start whenever your schedule allows. Tell us about the home and the project.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="Clear financing information for a full schedule.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances.",
  sit_h="No spare hours for financing research.",
  sit_p1="Between shifts, the last thing anyone wants is a drawn-out financing process. The comparison here is designed to need one form and one call.",
  sit_p2="What the cards cost now versus what a home-secured line costs over its repayment period. Totals, fees, the security trade. One conversation.",
  dist_h="The actual process, stated plainly",
  dist_p1="Form now, at any hour. Callback in business hours at a time you name. The comparison happens on that call; documents move by email only if you decide to continue.",
  dist_p2="No branch visits, no repeated forms, no invented urgency.",
  bens=["One form, one scheduled call",
        "Total-cost comparison, fees included",
        "The first mortgage stays as it is"],
  faqs=[{"q": "How fast does the callback come?", "a": "Usually within one business day. If you name a preferred window in the form, the specialist targets it within business hours."}],
  intake="Start at any hour. Name a callback window that fits the roster.",
  purpose="Debt consolidation")),

dict(slug="educators", label="Teachers and school staff", visual="project_board",
 ren=dict(
  title="HELOC for Educators: Home Projects | Stonehaven",
  h1="Give the next home project a plan.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you plan the project around the calendar that suits your household.",
  sit_h="Some households plan around a school year. The financing can too.",
  sit_p1="Plenty of homeowners, educators among them, prefer major work compressed into the windows that disrupt the household least. Builders know those windows; financing should be arranged before them, not during.",
  sit_p2="A line of credit suits that rhythm: set it up ahead of the window, draw when the work actually starts.",
  dist_h="Staging the project around your preferred timing",
  dist_p1="Work backward from when you want the work done: quotes a season early, financing comparison after quotes, line in place before the crew is booked.",
  dist_p2="A specialist can walk that timeline with you. The terms offered are the same for every homeowner; no occupation carries special pricing here, and we would rather say so than imply otherwise.",
  bens=["Financing arranged ahead of the project window",
        "Draw when the work starts, not before",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "How far ahead should financing be arranged?", "a": "Line setup involves underwriting and often a valuation, so starting a couple of months before you want funds available is comfortable. Exact timelines vary by lender and file.", "review": True}],
  intake="Tell us the project and the window you are aiming for. A specialist compares your options.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="A straightforward comparison for the next financial decision.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring card balances.",
  sit_h="A decision that rewards doing the homework.",
  sit_p1="The consolidation question is a homework question: what do the cards cost, what would the new structure cost, over how long, with what fees, secured by what.",
  sit_p2="We do the homework and show the working. Both totals, side by side, before any application.",
  dist_h="The working, shown",
  dist_p1="A specialist prepares the comparison from your rough numbers: current card cost, proposed structure cost across its full repayment period, fees itemized, the home-security trade stated in plain words.",
  dist_p2="Terms are the same for every homeowner; no occupation changes them. The decision is yours, made on shown working.",
  bens=["Both totals shown before any application",
        "Fees itemized, repayment period explicit",
        "The first mortgage stays as it is"],
  faqs=[{"q": "What numbers should I have ready?", "a": "Roughly: card balances and their costs, your home's estimated value and the mortgage balance. Estimates are fine to start; precision comes later with documents."}],
  intake="Share the rough numbers. A specialist shows the working.",
  purpose="Debt consolidation")),

dict(slug="contractor-quotes", label="Homeowners holding renovation quotes", visual="quotes",
 ren=dict(
  title="Quotes In? Compare Renovation Financing | Stonehaven",
  h1="The quotes are in. Now compare the financing.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you turn a quoted cost into a funded project.",
  sit_h="Three estimates on the table. One question left.",
  sit_p1="Once the quotes arrive, the project stops being hypothetical. The remaining question is which financing structure carries the number best.",
  sit_p2="This page is that comparison: a separate line against your equity, drawn as the builder invoices, next to the alternatives.",
  dist_h="From quoted cost to financed amount",
  dist_p1="Start with the quote you would actually accept. Add a contingency you choose deliberately rather than by default. That total, not the roundest number near it, is the amount worth financing.",
  dist_p2="A specialist takes it from there: sizing against equity, comparing line versus fixed structures, and mapping draws to the builder's payment schedule. We work with your chosen contractor's numbers; we do not recommend or endorse contractors.",
  bens=["Size the borrowing to the accepted quote plus your contingency",
        "Draws mapped to the builder's payment schedule",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Should I finance the lowest quote?", "a": "Finance the quote you would actually accept, which is not always the lowest. The financing comparison works with any of them; choosing the builder is your decision, not ours."}],
  intake="Tell us the quoted number and the timeline. A specialist compares the structures.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Project Balances | Stonehaven Lending",
  h1="Review existing project balances before funding the next stage.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring what earlier project stages left on cards.",
  sit_h="Stage one went on the cards. Stage two deserves a plan.",
  sit_p1="Plenty of renovations start on credit cards: deposits, materials, the surprise behind the wall. Before funding the next stage the same way, it is worth comparing a structure built for project costs.",
  sit_p2="A home-secured line can restructure the existing balances and fund what remains, in one comparison.",
  dist_h="Existing balances and remaining scope, together",
  dist_p1="List what the project has already put on cards, then the quoted cost of what remains. The comparison covers both: restructuring the first, funding the second, and the total cost of doing each.",
  dist_p2="The new borrowing is secured by your home, and a specialist prices the whole picture rather than the fragment that fits on a slogan.",
  bens=["One comparison covers past balances and remaining scope",
        "Total cost, fees and repayment period made explicit",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Can one line cover old balances and new work?", "a": "Commonly, yes, subject to equity and lender limits: proceeds restructure the card balances and remaining line capacity funds the next stage. A specialist confirms the sizing for your numbers.", "review": True}],
  intake="Share the balances and the remaining scope. A specialist prices the whole picture.",
  purpose="Debt consolidation")),

dict(slug="unfinished-projects", label="DIY renovators mid-project", visual="unfinished",
 ren=dict(
  title="Finish the Renovation: HELOC Options | Stonehaven",
  h1="The project got bigger than the weekend.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you fund a proper finish.",
  sit_h="Every renovator has met this room.",
  sit_p1="It started as a straightforward job, and then the house had opinions: the wall that was not what it seemed, the subfloor with a history, the scope that grew a zero. No shame in it; that is renovation.",
  sit_p2="Finishing well usually means a real budget and, often, trades. A separate line of credit funds that finish without touching the mortgage underneath.",
  dist_h="Done, remaining, and the number in between",
  dist_p1="Split the project three ways: work completed and paid for, work remaining you can still do yourself, and work remaining that needs professionals. Only the last two need financing, and only the third needs quotes.",
  dist_p2="A specialist sizes a line to that split. Eligibility depends on your equity and file like any other borrowing; a project in progress does not qualify or disqualify a home by itself.",
  bens=["Fund the professional finish, not the whole history",
        "Draw as the remaining stages happen",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Does a half-finished project affect the valuation?", "a": "It can, in either direction, depending on what stage the property is in when a lender values it. The honest answer comes from the lender's valuation during review.", "review": True}],
  intake="Tell us what is done and what remains. A specialist sizes the finish.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Project Card Balances | Stonehaven",
  h1="Compare options for existing project-related card balances.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring what the project has already cost.",
  sit_h="The materials went on the card. The card kept score.",
  sit_p1="Self-funded projects have a way of accumulating balances one supply run at a time. Once the pace slows, those balances deserve the same planning the project itself gets.",
  sit_p2="The comparison: what the balances cost where they sit, against a home-secured structure over its full repayment period.",
  dist_h="Balances first, next stage second",
  dist_p1="Restructure what exists before financing what is next; the comparison covers both so the sequencing is deliberate rather than accidental.",
  dist_p2="A specialist itemizes cost, fees and the repayment period, and is direct about the fact that the new borrowing is secured by the home the project lives in.",
  bens=["Project balances compared honestly against a new structure",
        "The next stage priced in the same conversation",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Do I need the project finished before applying?", "a": "Not necessarily, but property condition matters to lenders and their valuations. A specialist will tell you whether your stage of work is likely to matter for the option you want.", "review": True}],
  intake="Share the balances and the state of the project. A specialist runs the comparison.",
  purpose="Debt consolidation")),

dict(slug="someday-project", label="Homeowners with a postponed project", visual="inspiration",
 ren=dict(
  title="The Someday Kitchen: Make a Plan | Stonehaven",
  h1="That someday kitchen deserves a plan.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while someday gets a scope, a number and a comparison.",
  sit_h="The folder of saved ideas is not a plan. Yet.",
  sit_p1="Every postponed project lives somewhere: a board of saved photos, a drawer of samples, a mental note that renews itself each year. The gap between inspiration and renovation is usually one honest number.",
  sit_p2="There is no deadline here and no reason to manufacture one. When you want the number, this is how it gets made.",
  dist_h="From inspiration to scope to comparison",
  dist_p1="Turn the saved ideas into a one-page scope. Get it priced, even roughly. Then compare financing structures against that price: a line drawn in stages, a fixed loan, or waiting, which is always a legitimate option.",
  dist_p2="A specialist handles the third step whenever the first two are ready, and borrowing is never the required conclusion.",
  bens=["A real number instead of a renewing mental note",
        "Structures compared only when you are ready",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "Is there a right time to set up a line?", "a": "The practical answer: after the scope is real and before the builder is booked. Beyond that, timing is yours; nothing about the product expires."}],
  intake="Tell us about the project when you are ready. A specialist makes the number real.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC Before the Next Card Balance | Stonehaven",
  h1="Compare financing before the next project goes on a card.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare structures ahead of spending, not after.",
  sit_h="The cheapest time to compare is before the spending.",
  sit_p1="Projects funded reactively tend to land on cards; projects funded deliberately get compared first. The second group usually pays less for the same kitchen.",
  sit_p2="If earlier projects already left balances behind, the same comparison covers restructuring those too.",
  dist_h="Compare first, spend second",
  dist_p1="A specialist prices the structures against your rough scope before any commitment: line versus fixed versus not borrowing, with fees and repayment periods explicit.",
  dist_p2="The point is an informed default for the moment the project becomes real, not pressure to make it real today.",
  bens=["The comparison ready before the spending starts",
        "Existing balances can be included in the same look",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Does getting the comparison commit me to anything?", "a": "No. The comparison precedes any application and carries no obligation, and there is no hard credit pull to see it."}],
  intake="Share the rough shape of the project. A specialist prepares the comparison.",
  purpose="Debt consolidation")),

dict(slug="self-employed-homeowners", label="Self-employed homeowners", visual="workspace",
 ren=dict(
  title="HELOC for Self-Employed Homeowners | Stonehaven",
  h1="Self-employed? Start with your home equity and income questions.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place, and the documentation path for self-employed files is stated up front.",
  sit_h="You run the business. The house has its own backlog.",
  sit_p1="Self-employed homeowners tend to put the business's needs first and the house's projects somewhere behind quarterly obligations. When the project's turn comes, the financing questions are practical: what documents, how long, how sized.",
  sit_p2="Those questions have real answers, and they are better delivered straight than wrapped in promises.",
  dist_h="Income documentation, stated plainly",
  dist_p1="Stonehaven offers bank-statement HELOC options, subject to lender review. The lender verifies eligible income, expenses and business activity. Statement periods and documentation requirements depend on the program.",
  dist_p2="A specialist tells you which documentation path fits your file before you gather anything, so the process starts once and finishes.",
  bens=["The documentation path named before you start",
        "Fund the project in stages around business cash flow",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "What income documents do self-employed borrowers need?", "a": "Commonly two years of tax returns, or bank statements over a defined period on programs built for it. Which applies depends on the lender and your file; the specialist confirms before you gather documents.", "review": True}],
  intake="Tell us about the project and how the income is structured. A specialist names the path.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Credit Card Consolidation | Stonehaven",
  h1="A clear comparison for personal credit card balances.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring personal card balances. This page is about personal borrowing, not business credit.",
  sit_h="Business and personal, kept straight.",
  sit_p1="When work and life share a checkbook's orbit, personal card balances can quietly grow while attention stays on the business. This comparison is for the personal side: a homeowner's balances against a home-secured structure.",
  sit_p2="Business financing is a different conversation with different products; we will not blur the two.",
  dist_h="What the file will need",
  dist_p1="Self-employed income is verified with real documents: typically tax returns, or bank statements on programs designed for them. Knowing which path applies before you start saves the second round of paperwork.",
  dist_p2="The comparison itself needs only rough numbers: balances, home value, mortgage balance. Totals, fees and the repayment period come back in plain form.",
  bens=["Personal borrowing, clearly separated from business credit",
        "The documentation path named early",
        "The first mortgage stays as it is"],
  faqs=[{"q": "Can the line be used for my business?", "a": "This page and comparison address personal, homeowner borrowing. Lender rules on proceeds vary, and business-purpose lending is a separate conversation we are happy to have on its own terms.", "review": True}],
  intake="Share the personal balances and rough numbers. A specialist runs the comparison.",
  purpose="Debt consolidation")),

dict(slug="first-home-upgrades", label="Recent first-time homeowners", visual="boxes",
 ren=dict(
  title="First Home Upgrades: HELOC Options | Stonehaven",
  h1="First home. Next chapter: the kitchen.",
  sub="A HELOC is a separate line against your equity. Your first mortgage stays in place while you find out what your current equity actually supports.",
  sit_h="The boxes are unpacked. The cabinets are still 1987.",
  sit_p1="First homes are usually bought for the bones and the address, with a mental list of what changes later. Later arrives faster than expected.",
  sit_p2="The honest starting question for a newer owner is not which countertop; it is how much eligible equity exists today. That number decides everything else.",
  dist_h="Equity and seasoning come first",
  dist_p1="Equity is your home's current value minus what you owe, and lenders lend against only part of it. Some lenders also apply seasoning requirements, meaning a minimum time owned before certain borrowing. Owning a home does not by itself create borrowing capacity, especially early.",
  dist_p2="A specialist checks both against your numbers before the project conversation, so the plan is built on what is actually available.",
  bens=["Find out what current equity supports before designing",
        "Seasoning rules checked up front, not at the finish line",
        "The existing first mortgage stays as it is"],
  faqs=[{"q": "How soon after buying can I open a HELOC?", "a": "It depends on the lender's seasoning rules and on how much eligible equity exists at today's value. Some files support it early, many need more time or more equity. A specialist checks yours specifically.", "review": True}],
  intake="Tell us when you bought and the rough numbers. A specialist checks what is supportable.",
  purpose="Home improvement"),
 con=dict(
  title="HELOC for Home-Project Card Balances | Stonehaven",
  h1="Compare a plan for home-project card balances.",
  sub="A HELOC is a separate loan secured by your home. Your first mortgage stays in place while you compare restructuring what the first year of ownership put on cards.",
  sit_h="The first year of ownership has a receipt trail.",
  sit_p1="New homeowners spend: appliances, repairs the inspection undersold, the room that could not stay carpet. Much of it lands on cards, and a year in, those balances are worth a structured look.",
  sit_p2="Whether a home-secured line can restructure them depends on the equity that exists now, which for newer owners is the first thing to verify.",
  dist_h="What current equity actually supports",
  dist_p1="Lenders lend against part of your equity, after the mortgage balance, and some apply time-owned requirements. Early in ownership the supportable amount may be smaller than the balances, and it is better to know that in minutes than after an application.",
  dist_p2="A specialist runs that check first, then the cost comparison only if the sizing works.",
  bens=["Sizing reality checked before the cost comparison",
        "Total cost, fees and repayment period made explicit",
        "The first mortgage stays as it is"],
  faqs=[{"q": "What if my equity is not enough yet?", "a": "Then the honest answer is to wait or look at other approaches, and we will say so. Nothing about this comparison assumes borrowing must happen."}],
  intake="Tell us when you bought and the rough numbers. A specialist checks the sizing first.",
  purpose="Debt consolidation")),
]
