# -*- coding: utf-8 -*-
"""Message-matched landing pages for the Meta ad set "SEND TO NEW LANDING PAGES"
(HELOC / cash-out refi campaign). One page per ad; hero mirrors the ad's
on-image headline and support line. Edit here, then:
python3 scripts/build-heloc-ads.py
Module types: checks, timeline, ladder, estimator, table, diagram, consolidation.
Claims rules: no rates, no guarantees, "no hard credit pull to compare initial
options" (never "no credit check"), credit floor always "600+ considered",
second-position HELOC leaves the first mortgage in place (never "payments stay
the same"), VA loans: not a VA product, no government affiliation."""

DISCLOSURE = ("Equal Housing Opportunity. Stonehaven Lending is a mortgage brokerage, not a direct lender. "
              "NMLS #1752355. Home loans in GA, AL, TN, FL, NC and SC. Estimates only, subject to verification, "
              "credit approval and lender underwriting.")

ADS = [
dict(slug="no-credit-impact", ad="NO CREDIT HIT CHECK", purpose="Home improvement",
 title="Checking HELOC Options Won't Affect Credit | Stonehaven",
 eyebrow="Soft credit pull", h1="Checking options won't affect credit scores",
 sub="A soft inquiry returns estimated options in minutes. A hard pull happens only if an application moves forward. Credit scores 600+ considered.",
 cta="See what's available",
 modules=[dict(type="timeline", h="What happens to your credit, and when",
   items=[("Now: estimate","Enter a rough home value and mortgage balance. No credit inquiry of any kind at this step; the estimate is arithmetic on your numbers."),
          ("Comparing options: soft inquiry","When a specialist compares initial options, a soft credit inquiry may be used. Soft inquiries are not visible to other lenders and do not affect credit scores."),
          ("Only if you apply: hard pull","A hard inquiry happens only if you choose to move an application forward with a lender. You will know before it happens.")]),
   dict(type="estimator")],
 faqs=[("Does a soft inquiry show up on my credit report?","Soft inquiries appear only to you on your own report; other lenders do not see them and they do not affect scores."),
       ("When exactly would a hard pull happen?","Only if you decide to submit a full application with a lender, after comparing options. It is never part of the estimate or the initial comparison."),
       ("Is 600+ a promise of approval?","No. It describes where consideration typically begins. Credit, equity, income documentation and program rules all decide.")]),

dict(slug="terms-stated-plainly", ad="FICO FLOOR", purpose="Home improvement",
 title="HELOC Terms, Stated Plainly | Stonehaven Lending",
 eyebrow="Program terms", h1="The terms, stated plainly",
 sub="No rate teasers, no promises underwriting cannot keep. Four things that are true before anyone applies.",
 cta="Get my estimate",
 modules=[dict(type="checks", h="Four things that are true",
   items=["Credit scores 600+ considered","Second position: the existing first mortgage stays untouched","No hard credit pull to compare initial options","No appraiser visit to get started; full valuation requirements depend on the program"]),
   dict(type="estimator")],
 faqs=[("What does 'second position' mean?","The HELOC is a separate second lien behind your existing first mortgage. The first mortgage and its terms stay exactly as they are; the HELOC adds its own payment."),
       ("Will I need an appraisal eventually?","Getting started needs no appraiser visit. Whether a full appraisal is required later depends on the program and the lender; many home equity lines use automated or drive-by valuations."),
       ("Why are there no rates on this page?","Because a rate depends on your credit, equity, program and the day you lock. A number on an ad page would be a teaser, and we do not publish those.")]),

dict(slug="how-much-equity", ad="AMOUNT LADDER", purpose="Home improvement",
 title="How Much Home Equity Could Be Available? | Stonehaven",
 eyebrow="Estimated available amounts", h1="How much equity could be available?",
 sub="Pick the amount you are thinking about, then see an estimated range before speaking with anyone. Available amounts depend on equity, credit and program guidelines.",
 cta="See how much",
 modules=[dict(type="ladder", h="Start with the amount you have in mind", amounts=[50000,100000,200000,300000]),
   dict(type="estimator")],
 faqs=[("Is the ladder amount what I would get?","No. It records what you are exploring. The estimate below shows the range your equity may support at common lender caps, and a specialist confirms the real figure."),
       ("What decides the actual available amount?","Your home's value, your mortgage balance, the lender's combined loan-to-value limit, your credit profile and the program's rules."),
       ("Can I ask for less than the estimate shows?","Yes. A line of credit can be sized to what you need; you are not obliged to take the maximum.")]),

dict(slug="renovate-keep-your-rate", ad="HOME IMPROVEMENT", purpose="Home improvement",
 title="Renovate Without Touching the Mortgage Rate | Stonehaven",
 eyebrow="Renovation funding", h1="Renovate without touching the mortgage rate",
 sub="A second-position home equity line funds the project while the existing first mortgage stays exactly as it is, at the rate it already has. No refinancing required.",
 cta="Calculate my estimate",
 modules=[dict(type="estimator"),
   dict(type="checks", h="How renovation funding on a line works",
   items=["Draw funds in stages as the contractor invoices, not all at once","Interest accrues on what you have drawn, not the whole line","The first mortgage and its rate are untouched; the line is its own loan with its own payment","Credit scores 600+ considered; no hard credit pull to compare initial options"])],
 faqs=[("Do I have to take the whole amount at once?","No. A line of credit is drawn as needed during its draw period, which suits staged renovation costs."),
       ("Does this change my current mortgage?","No. The HELOC sits in second position behind it. Your first mortgage keeps its balance, rate and payment; the HELOC adds a separate payment."),
       ("Is a fixed home equity loan better for a renovation?","For one known contract price, a fixed second loan can suit; for staged or uncertain costs, a line usually fits better. A specialist compares both for your project.")]),

dict(slug="veteran-equity", ad="VETERAN EQUITY", purpose="Home improvement",
 title="Access Home Equity Without Refinancing a VA Loan | Stonehaven",
 eyebrow="For veteran homeowners", h1="Access home equity without refinancing",
 sub="Veteran homeowners may be able to access home equity while leaving an existing VA loan and its rate in place. A second-position line sits behind the original loan. Credit scores 600+ considered.",
 cta="See what's available",
 modules=[dict(type="table", h="The existing VA loan and a second-position line",
   cols=("","Existing VA first mortgage","Second-position HELOC"),
   rows=[("What happens to it","Stays exactly as it is: balance, rate, payment","New, separate loan added behind it"),
         ("Is refinancing required","No","No; the first mortgage is untouched"),
         ("Government backing","VA guaranty per VA rules","None; a conventional, privately funded product"),
         ("Who can use it","Eligible veterans per VA rules","Any qualifying homeowner; terms do not depend on service history")]),
   dict(type="estimator")],
 faqs=[("Is this a VA home equity loan?","No. A HELOC is not a VA product, is not backed by the VA or any government agency, and Stonehaven is not affiliated with the government. It is a conventional second lien that happens to sit behind a VA first mortgage."),
       ("Does opening a HELOC affect my VA loan?","Your VA loan continues unchanged. Check your VA loan documents for any lender notification requirements on secondary financing; a specialist can help read them."),
       ("Do veterans get different terms?","No. Terms follow the property, equity, credit and program. This page exists because the accurate answer is useful, not because service status changes the offer.")]),

dict(slug="one-payment", ad="DEBT CONSOLIDATION", purpose="Debt consolidation",
 title="Compare HELOC Debt Consolidation Costs | Stonehaven",
 eyebrow="Debt consolidation", h1="Compare a different repayment plan for your balances",
 sub="Compare payments, fees and remaining debt at the same future date. Your first mortgage may keep its own payment, and the new borrowing is secured by your home.",
 cta="See how much",
 modules=[dict(type="consolidation", h="Several balances, one home-secured plan",
   note="Consolidating unsecured balances into a loan secured by your home restructures the debt; it does not erase it. The comparison worth making is total cost over the full repayment period, fees included, against what the cards cost today."),
   dict(type="estimator")],
 faqs=[("Will one payment be lower than my card payments combined?","It depends on the offer and your current balances. A lower monthly payment stretched over more years can cost more in total. A specialist shows both the payment and the total cost so the decision uses the whole picture."),
       ("What does 'secured by the home' mean for me?","The HELOC is a lien on your home. If repayment fails, the home is at risk in a way unsecured card debt never put it. That trade belongs at the front of the decision, not the fine print."),
       ("Does consolidating hurt or help credit?","Paying revolving balances may change utilization, and individual results vary. No outcome is promised; checking initial options involves no hard credit pull.")]),

dict(slug="cash-out-refi-or-heloc", ad="EXPLAINER", purpose="Home improvement",
 title="Cash-Out Refi or Home Equity Loan? A Plain Compare | Stonehaven",
 eyebrow="A plain-English compare", h1="Cash-out refi, or home equity loan?",
 sub="Two ways to access home equity, side by side. A cash-out refinance replaces the first mortgage: one loan, one payment, at today's rate. A home equity loan or HELOC sits behind it: two payments, and the original rate stays. Which fits depends on the rate on the existing loan, the amount needed and the timeline.",
 cta="Compare my options",
 modules=[dict(type="table", h="Side by side",
   cols=("","Cash-out refinance","Home equity loan or HELOC"),
   rows=[("Your current first mortgage","Replaced by a new, larger loan","Stays exactly as it is"),
         ("Number of payments","One","Two: the first mortgage plus the second loan"),
         ("Rate on the existing balance","Reset to a new rate for the whole balance","Untouched; only the new borrowing carries a new rate"),
         ("How funds arrive","Lump sum at closing","Lump sum (equity loan) or draw as needed (HELOC)"),
         ("Usually fits when","The current rate is at or above today's market","The current rate is worth keeping")]),
   dict(type="estimator")],
 faqs=[("Which one is cheaper?","It depends on the rate you already have. Replacing a low-rate first mortgage to reach equity can cost far more than a second loan; replacing a high-rate one can make sense. A specialist runs both on your numbers."),
       ("Can I do a cash-out refinance through Stonehaven?","Yes. Stonehaven arranges both cash-out refinancing and second-position home equity financing, so the comparison is genuinely neutral."),
       ("What if I am not sure which I want?","Send the numbers. The comparison comes first and the recommendation follows the math, including when the right answer is neither.")]),

dict(slug="keep-your-rate", ad="LOCK IN HERO", purpose="Home improvement",
 title="Access Your Equity. Keep Your Rate | Stonehaven Lending",
 eyebrow="Home equity line of credit", h1="Access your equity. Keep your rate",
 sub="Homeowners may be able to access equity through a second-position HELOC. The existing first mortgage stays in place, at the rate it already has. No refinancing of the first loan required.",
 cta="Get my estimate",
 modules=[dict(type="diagram"), dict(type="estimator")],
 faqs=[("Does keeping my rate mean my monthly costs do not change?","No. Your first mortgage payment is unchanged; the HELOC adds its own second payment with its own costs. Total monthly outgo goes up by the HELOC payment."),
       ("Is this a refinance?","No. The first mortgage is not refinanced or changed. The HELOC is a separate second lien on the same home."),
       ("How fast can I see a number?","The estimate is instant from the value and balance you enter. A specialist confirms the real figure on a callback, usually within one business day.")]),
]
